In [7]:
import pandas as pd

In [9]:
bank = pd.read_csv('bank3.csv')

In [13]:
# bank.drop(["A", "B", "C", "D", "E"], axis=1, inplace=True)
# bank.drop(["CHQ.NO."], axis=1, inplace=True)

In [16]:
bank

,Account No,DATE,TRANSACTION DETAILS,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT
0,409000611074,2017-06-29,TRF FROM Indiaforensic SERVICES,2017-06-29,NaN,1000000.0,1.000000e+06
1,409000611074,2017-07-05,TRF FROM Indiaforensic SERVICES,2017-07-05,NaN,1000000.0,2.000000e+06
2,409000611074,2017-07-18,FDRL/INTERNAL FUND TRANSFE,2017-07-18,NaN,500000.0,2.500000e+06
3,409000611074,2017-08-01,TRF FRM Indiaforensic SERVICES,2017-08-01,NaN,3000000.0,5.500000e+06
4,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,6.000000e+06
5,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,6.500000e+06
6,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,7.000000e+06
7,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,7.500000e+06
8,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,8.000000e+06
9,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,8.500000e+06
10,409000611074,2017-08-16,INDO GIBL Indiaforensic STL01071,2017-08-16,133900.00,NaN,8.366100e+06
11,409000611074,2017-08-16,INDO GIBL Indiaforensic STL02071,2017-08-16,18000.00,NaN,8.348100e+06
12,409000611074,2017-08-16,INDO GIBL Indiaforensic STL03071,2017-08-16,5000.00,NaN,8.343100e+06
13,409000611074,2017-08-16,INDO GIBL Indiaforensic STL04071,2017-08-16,195800.00,NaN,8.147300e+06
14,409000611074,2017-08-16,INDO GIBL Indiaforensic STL05071,2017-08-16,81600.00,NaN,8.065700e+06
15,409000611074,2017-08-16,INDO GIBL Indiaforensic STL06071,2017-08-16,41800.00,NaN,8.023900e+06
16,409000611074,2017-08-16,INDO GIBL Indiaforensic STL07071,2017-08-16,98500.00,NaN,7.925400e+06
17,409000611074,2017-08-16,INDO GIBL Indiaforensic STL10071,2017-08-16,143800.00,NaN,7.781600e+06
18,409000611074,2017-08-16,INDO GIBL Indiaforensic STL11071,2017-08-16,331650.00,NaN,7.449950e+06
19,409000611074,2017-08-16,INDO GIBL Indiaforensic STL12071,2017-08-16,129000.00,NaN,7.320950e+06
20,409000611074,2017-08-16,INDO GIBL Indiaforensic STL13071,2017-08-16,230013.00,NaN,7.090937e+06
21,409000611074,2017-08-16,INDO GIBL Indiaforensic STL14071,2017-08-16,367900.00,NaN,6.723037e+06
22,409000611074,2017-08-16,INDO GIBL Indiaforensic STL15071,2017-08-16,108000.00,NaN,6.615037e+06
23,409000611074,2017-08-16,INDO GIBL Indiaforensic STL16071,2017-08-16,64800.00,NaN,6.550237e+06
24,409000611074,2017-08-16,INDO GIBL Indiaforensic STL17071,2017-08-16,141000.00,NaN,6.409237e+06
25,409000611074,2017-08-16,INDO GIBL Indiaforensic STL18071,2017-08-16,61750.00,NaN,6.347487e+06
26,409000611074,2017-08-16,INDO GIBL Indiaforensic STL19071,2017-08-16,67920.00,NaN,6.279567e+06
27,409000611074,2017-08-16,INDO GIBL Indiaforensic STL20071,2017-08-16,78100.00,NaN,6.201467e+06
28,409000611074,2017-08-16,INDO GIBL Indiaforensic STL21071,2017-08-16,35650.00,NaN,6.165817e+06
29,409000611074,2017-08-16,INDO GIBL Indiaforensic STL22071,2017-08-16,206000.00,NaN,5.959817e+06
...,...,...,...,...,...,...,...
116171,409000362497,2019-03-02,Sweep Trf To: 40900036427,2019-03-02,4000.00,NaN,-1.900463e+09
116172,409000362497,2019-03-04,IMPS 0203191C,2019-03-04,8902.39,NaN,-1.900472e+09
116173,409000362497,2019-03-04,IMPS 0303191C,2019-03-04,67752.22,NaN,-1.900540e+09
116174,409000362497,2019-03-04,IMPS 040320192C,2019-03-04,431613.76,NaN,-1.900971e+09
116175,409000362497,2019-03-04,IMPS 040320193C,2019-03-04,348262.41,NaN,-1.901320e+09
116176,409000362497,2019-03-04,FDRL/INTERNAL FUND TRANSFE,2019-03-04,NaN,1000000.0,-1.900320e+09
116177,409000362497,2019-03-04,FDRL/INTERNAL FUND TRANSFE,2019-03-04,NaN,300000.0,-1.900020e+09
116178,409000362497,2019-03-04,NEFT/SBIN619063713746/Indfor,2019-03-04,NaN,1200000.0,-1.898820e+09
116179,409000362497,2019-03-04,IMPS 040320194C,2019-03-04,83802.03,NaN,-1.898904e+09
116180,409000362497,2019-03-04,Sweep Trf To: 40900036427,2019-03-04,8000.00,NaN,-1.898912e+09
116181,409000362497,2019-03-05,IMPS 0403191C,2019-03-05,20185.23,NaN,-1.898932e+09
116182,409000362497,2019-03-05,IMPS 050320192C,2019-03-05,548690.97,NaN,-1.899480e+09
116183,409000362497,2019-03-05,IMPS 050320193C,2019-03-05,425622.38,NaN,-1.899906e+09
116184,409000362497,2019-03-05,FDRL/INTERNAL FUND TRANSFE,2019-03-05,NaN,1000000.0,-1.898906e+09
116185,409000362497,2019-03-05,FDRL/INTERNAL FUND TRANSFE,2019-03-05,NaN,1000000.0,-1.897906e+09
116186,409000362497,2019-03-05,FDRL/INTERNAL FUND TRANSFE,2019-03-05,NaN,1000000.0,-1.896906e+09
116187,409000362497,2019-03-05,NEFT/000069177649/INDIAID,2019-03-05,6599.00,NaN,-1.896913e+09
116188,409000362497,2019-03-05,NEFT/000069177816/PAYU PA,2019-03-05,37251.00,NaN,-1.896950e+09
116189,409000362497,2019-03-05,NEFT/000069177962/FUTURE,2019-03-05,2829.00,NaN,-1.896953e+09
116190,409000362497,2019-03-05,NEFT/000069178285/PASFAR,2019-03-05,98.00,NaN,-1.896953e+09
116191,409000362497,2019-03-05,NEFT/000069178432/MEHAR E,2019-03-05,230.00,NaN,-1.896953e+09
116192,409000362497,2019-03-05,NEFT/000069178587/INDIAN,2019-03-05,816832.00,NaN,-1.897770e+09
116193,409000362497,2019-03-05,NEFT/000069178631/INDIAN,2019-03-05,1699952.16,NaN,-1.899470e+09
116194,409000362497,2019-03-05,NEFT/000069179261/INDIAN,2019-03-05,1095668.87,NaN,-1.900565e+09
116195,409000362497,2019-03-05,NEFT/000069179347/INDIAN,2019-03-05,1218673.00,NaN,-1.901784e+09
116196,409000362497,2019-03-05,TRF TO 1196428 Indiaforensic SE,2019-03-05,117934.30,NaN,-1.901902e+09
116197,409000362497,2019-03-05,FDRL/INTERNAL FUND TRANSFE,2019-03-05,NaN,300000.0,-1.901602e+09
116198,409000362497,2019-03-05,FDRL/INTERNAL FUND TRANSFE,2019-03-05,NaN,300000.0,-1.901302e+09
116199,409000362497,2019-03-05,IMPS 05-03-20194C,2019-03-05,109868.65,NaN,-1.901412e+09
116200,409000362497,2019-03-05,Sweep Trf To: 40900036427,2019-03-05,5000.00,NaN,-1.901417e+09

In [52]:
df_acc1 = bank[bank["Account No"] == 409000611074]
df_acc1

,Account No,DATE,TRANSACTION DETAILS,VALUE DATE,WITHDRAWAL AMT,DEPOSIT AMT,BALANCE AMT
0,409000611074,2017-06-29,TRF FROM Indiaforensic SERVICES,2017-06-29,NaN,1000000.0,1000000.0
1,409000611074,2017-07-05,TRF FROM Indiaforensic SERVICES,2017-07-05,NaN,1000000.0,2000000.0
2,409000611074,2017-07-18,FDRL/INTERNAL FUND TRANSFE,2017-07-18,NaN,500000.0,2500000.0
3,409000611074,2017-08-01,TRF FRM Indiaforensic SERVICES,2017-08-01,NaN,3000000.0,5500000.0
4,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,6000000.0
5,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,6500000.0
6,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,7000000.0
7,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,7500000.0
8,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,8000000.0
9,409000611074,2017-08-16,FDRL/INTERNAL FUND TRANSFE,2017-08-16,NaN,500000.0,8500000.0
10,409000611074,2017-08-16,INDO GIBL Indiaforensic STL01071,2017-08-16,133900.0,NaN,8366100.0
11,409000611074,2017-08-16,INDO GIBL Indiaforensic STL02071,2017-08-16,18000.0,NaN,8348100.0
12,409000611074,2017-08-16,INDO GIBL Indiaforensic STL03071,2017-08-16,5000.0,NaN,8343100.0
13,409000611074,2017-08-16,INDO GIBL Indiaforensic STL04071,2017-08-16,195800.0,NaN,8147300.0
14,409000611074,2017-08-16,INDO GIBL Indiaforensic STL05071,2017-08-16,81600.0,NaN,8065700.0
15,409000611074,2017-08-16,INDO GIBL Indiaforensic STL06071,2017-08-16,41800.0,NaN,8023900.0
16,409000611074,2017-08-16,INDO GIBL Indiaforensic STL07071,2017-08-16,98500.0,NaN,7925400.0
17,409000611074,2017-08-16,INDO GIBL Indiaforensic STL10071,2017-08-16,143800.0,NaN,7781600.0
18,409000611074,2017-08-16,INDO GIBL Indiaforensic STL11071,2017-08-16,331650.0,NaN,7449950.0
19,409000611074,2017-08-16,INDO GIBL Indiaforensic STL12071,2017-08-16,129000.0,NaN,7320950.0
20,409000611074,2017-08-16,INDO GIBL Indiaforensic STL13071,2017-08-16,230013.0,NaN,7090937.0
21,409000611074,2017-08-16,INDO GIBL Indiaforensic STL14071,2017-08-16,367900.0,NaN,6723037.0
22,409000611074,2017-08-16,INDO GIBL Indiaforensic STL15071,2017-08-16,108000.0,NaN,6615037.0
23,409000611074,2017-08-16,INDO GIBL Indiaforensic STL16071,2017-08-16,64800.0,NaN,6550237.0
24,409000611074,2017-08-16,INDO GIBL Indiaforensic STL17071,2017-08-16,141000.0,NaN,6409237.0
25,409000611074,2017-08-16,INDO GIBL Indiaforensic STL18071,2017-08-16,61750.0,NaN,6347487.0
26,409000611074,2017-08-16,INDO GIBL Indiaforensic STL19071,2017-08-16,67920.0,NaN,6279567.0
27,409000611074,2017-08-16,INDO GIBL Indiaforensic STL20071,2017-08-16,78100.0,NaN,6201467.0
28,409000611074,2017-08-16,INDO GIBL Indiaforensic STL21071,2017-08-16,35650.0,NaN,6165817.0
29,409000611074,2017-08-16,INDO GIBL Indiaforensic STL22071,2017-08-16,206000.0,NaN,5959817.0
...,...,...,...,...,...,...,...
1063,409000611074,2019-01-21,INDO GIBL Indiaforensic STL20011,2019-01-21,96200.0,NaN,1451510.0
1064,409000611074,2019-01-21,FDRL/INTERNAL FUND TRANSFE,2019-01-21,NaN,300000.0,1751510.0
1065,409000611074,2019-01-22,Indfor INCOME INDO REMI21011,2019-01-22,4080.0,NaN,1747430.0
1066,409000611074,2019-01-22,INDO GIBL Indiaforensic STL21011,2019-01-22,602930.0,NaN,1144500.0
1067,409000611074,2019-01-22,FDRL/INTERNAL FUND TRANSFE,2019-01-22,NaN,400000.0,1544500.0
1068,409000611074,2019-01-23,Indfor INCOME INDO REMI22011,2019-01-23,3720.0,NaN,1540780.0
1069,409000611074,2019-01-23,INDO GIBL Indiaforensic STL22011,2019-01-23,589137.0,NaN,951643.0
1070,409000611074,2019-01-23,FDRL/INTERNAL FUND TRANSFE,2019-01-23,NaN,500000.0,1451643.0
1071,409000611074,2019-01-24,Indfor INCOME INDO REMI23011,2019-01-24,2880.0,NaN,1448763.0
1072,409000611074,2019-01-24,INDO GIBL Indiaforensic STL23011,2019-01-24,388327.0,NaN,1060436.0
1073,409000611074,2019-01-24,FDRL/INTERNAL FUND TRANSFE,2019-01-24,NaN,500000.0,1560436.0
1074,409000611074,2019-01-25,Indfor INCOME INDO REMI24011,2019-01-25,2040.0,NaN,1558396.0
1075,409000611074,2019-01-25,INDO GIBL Indiaforensic STL24011,2019-01-25,245413.0,NaN,1312983.0
1076,409000611074,2019-01-25,FDRL/INTERNAL FUND TRANSFE,2019-01-25,NaN,300000.0,1612983.0
1077,409000611074,2019-01-28,Indfor INCOME INDO REMI25011,2019-01-28,1920.0,NaN,1611063.0
1078,409000611074,2019-01-28,INDO GIBL Indiaforensic STL25011,2019-01-28,466124.0,NaN,1144939.0
1079,409000611074,2019-01-28,Indfor INCOME INDO REMI26011,2019-01-28,360.0,NaN,1144579.0
1080,409000611074,2019-01-28,INDO GIBL Indiaforensic STL26011,2019-01-28,17500.0,NaN,1127079.0
1081,409000611074,2019-01-28,FDRL/INTERNAL FUND TRANSFE,2019-01-28,NaN,400000.0,1527079.0
1082,409000611074,2019-01-29,Indfor INCOME INDO REMI28011,2019-01-29,2520.0,NaN,1524559.0
1083,409000611074,2019-01-29,INDO GIBL Indiaforensic STL28011,2019-01-29,299125.0,NaN,1225434.0
1084,409000611074,2019-01-29,FDRL/INTERNAL FUND TRANSFE,2019-01-29,NaN,300000.0,1525434.0
1085,409000611074,2019-01-30,Indfor INCOME INDO REMI29011,2019-01-30,3360.0,NaN,1522074.0
1086,409000611074,2019-01-30,INDO GIBL Indiaforensic STL29011,2019-01-30,401052.0,NaN,1121022.0
1087,409000611074,2019-01-31,Indfor INCOME INDO REMI30011,2019-01-31,1200.0,NaN,1119822.0
1088,409000611074,2019-01-31,INDO GIBL Indiaforensic STL30011,2019-01-31,224051.0,NaN,895771.0
1089,409000611074,2019-01-31,FDRL/INTERNAL FUND TRANSFE,2019-01-31,NaN,300000.0,1195771.0
1090,409000611074,2019-02-01,Indfor INCOME INDO REMI31011,2019-02-01,720.0,NaN,1195051.0
1091,409000611074,2019-02-01,INDO GIBL Indiaforensic STL31011,2019-02-01,132851.0,NaN,1062200.0
1092,409000611074,2019-02-08,FDRL/INTERNAL FUND TRANSFE,2019-02-08,600000.0,NaN,462200.0

In [61]:
from fuzzywuzzy import fuzz

df_acc1 = bank[bank["Account No"] == 409000611074]

def seq_match(df_temp, trans_details):
    
    df_temp.reset_index(inplace=True)
#     df_res = pd.DataFrame()
    df_res = []
    for i, (x, y) in enumerate(df_temp.iterrows()):
        if fuzz.ratio(trans_details, df_temp.loc[i, "TRANSACTION DETAILS"]) > 45:
            df_res.append(df_temp.loc[i]) 
#             print(i)
#         if fuzz.ratio(trans_details, df_temp.loc[i, "TRANSACTION DETAILS"]) > 45:
#             df
    
    return pd.DataFrame(df_res) 

trans_details = "TRF FROM Indiaforensic SERVICES"

res = seq_match(df_acc1, trans_details)
# res.reset_index(inplace=True)
print(res)

      index    Account No        DATE               TRANSACTION DETAILS  \
0         0  409000611074  2017-06-29  TRF FROM  Indiaforensic SERVICES
1         1  409000611074  2017-07-05  TRF FROM  Indiaforensic SERVICES
3         3  409000611074  2017-08-01   TRF FRM  Indiaforensic SERVICES
10       10  409000611074  2017-08-16  INDO GIBL Indiaforensic STL01071
11       11  409000611074  2017-08-16  INDO GIBL Indiaforensic STL02071
12       12  409000611074  2017-08-16  INDO GIBL Indiaforensic STL03071
13       13  409000611074  2017-08-16  INDO GIBL Indiaforensic STL04071
14       14  409000611074  2017-08-16  INDO GIBL Indiaforensic STL05071
15       15  409000611074  2017-08-16  INDO GIBL Indiaforensic STL06071
16       16  409000611074  2017-08-16  INDO GIBL Indiaforensic STL07071
17       17  409000611074  2017-08-16  INDO GIBL Indiaforensic STL10071
18       18  409000611074  2017-08-16  INDO GIBL Indiaforensic STL11071
19       19  409000611074  2017-08-16  INDO GIBL Indiaforensic STL12071
20       20  409000611074  2017-08-16  INDO GIBL Indiaforensic STL13071
21       21  409000611074  2017-08-16  INDO GIBL Indiaforensic STL14071
22       22  409000611074  2017-08-16  INDO GIBL Indiaforensic STL15071
23       23  409000611074  2017-08-16  INDO GIBL Indiaforensic STL16071
24       24  409000611074  2017-08-16  INDO GIBL Indiaforensic STL17071
25       25  409000611074  2017-08-16  INDO GIBL Indiaforensic STL18071
26       26  409000611074  2017-08-16  INDO GIBL Indiaforensic STL19071
27       27  409000611074  2017-08-16  INDO GIBL Indiaforensic STL20071
28       28  409000611074  2017-08-16  INDO GIBL Indiaforensic STL21071
29       29  409000611074  2017-08-16  INDO GIBL Indiaforensic STL22071
30       30  409000611074  2017-08-16  INDO GIBL Indiaforensic STL24071
31       31  409000611074  2017-08-16  INDO GIBL Indiaforensic STL25071
32       32  409000611074  2017-08-16  INDO GIBL Indiaforensic STL26071
33       33  409000611074  2017-08-16  INDO GIBL Indiaforensic STL27071
34       34  409000611074  2017-08-16  INDO GIBL Indiaforensic STL28071
35       35  409000611074  2017-08-16  INDO GIBL Indiaforensic STL30071
36       36  409000611074  2017-08-16  INDO GIBL Indiaforensic STL31071
...     ...           ...         ...                               ...
1004   1004  409000611074  2019-01-02  INDO GIBL Indiaforensic STL01011
1007   1007  409000611074  2019-01-03  INDO GIBL Indiaforensic STL02011
1011   1011  409000611074  2019-01-04  INDO GIBL Indiaforensic STL03011
1015   1015  409000611074  2019-01-05  INDO GIBL Indiaforensic STL04011
1017   1017  409000611074  2019-01-07  INDO GIBL Indiaforensic STL06011
1019   1019  409000611074  2019-01-07  INDO GIBL Indiaforensic STL05011
1023   1023  409000611074  2019-01-08  INDO GIBL Indiaforensic STL07011
1026   1026  409000611074  2019-01-09  INDO GIBL Indiaforensic STL08011
1030   1030  409000611074  2019-01-10  INDO GIBL Indiaforensic STL09011
1033   1033  409000611074  2019-01-11  INDO GIBL Indiaforensic STL10011
1037   1037  409000611074  2019-01-14  INDO GIBL Indiaforensic STL11011
1039   1039  409000611074  2019-01-14  INDO GIBL Indiaforensic STL12011
1041   1041  409000611074  2019-01-14  INDO GIBL Indiaforensic STL13011
1045   1045  409000611074  2019-01-15  INDO GIBL Indiaforensic STL14011
1048   1048  409000611074  2019-01-16  INDO GIBL Indiaforensic STL15011
1051   1051  409000611074  2019-01-17  INDO GIBL Indiaforensic STL16011
1054   1054  409000611074  2019-01-18  INDO GIBL Indiaforensic STL17011
1057   1057  409000611074  2019-01-19  INDO GIBL Indiaforensic STL18011
1061   1061  409000611074  2019-01-21  INDO GIBL Indiaforensic STL19011
1063   1063  409000611074  2019-01-21  INDO GIBL Indiaforensic STL20011
1066   1066  409000611074  2019-01-22  INDO GIBL Indiaforensic STL21011
1069   1069  409000611074  2019-01-23  INDO GIBL Indiaforensic STL22011
1072   1072  409000611074  2019-01-24  INDO GIBL Indiaforensic STL23011
1075   1075  409000611074  2019-01-25  INDO GIBL Indiaforensic STL24011
1078   1078  409000611074  2019-01-28  INDO GIBL Indiaforensic STL25011
1080   1080  409000611074  2019-01-28  INDO GIBL Indiaforensic STL26011
1083   1083  409000611074  2019-01-29  INDO GIBL Indiaforensic STL28011
1086   1086  409000611074  2019-01-30  INDO GIBL Indiaforensic STL29011
1088   1088  409000611074  2019-01-31  INDO GIBL Indiaforensic STL30011
1091   1091  409000611074  2019-02-01  INDO GIBL Indiaforensic STL31011

      VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0     2017-06-29             NaN    1000000.0    1000000.0
1     2017-07-05             NaN    1000000.0    2000000.0
3     2017-08-01             NaN    3000000.0    5500000.0
10    2017-08-16        133900.0          NaN    8366100.0
11    2017-08-16         18000.0          NaN    8348100.0
12    2017-08-16          5000.0          NaN    8343100.0
13    2017-08-16        195800.0          NaN    8147300.0
14    2017-08-16         81600.0          NaN    8065700.0
15    2017-08-16         41800.0          NaN    8023900.0
16    2017-08-16         98500.0          NaN    7925400.0
17    2017-08-16        143800.0          NaN    7781600.0
18    2017-08-16        331650.0          NaN    7449950.0
19    2017-08-16        129000.0          NaN    7320950.0
20    2017-08-16        230013.0          NaN    7090937.0
21    2017-08-16        367900.0          NaN    6723037.0
22    2017-08-16        108000.0          NaN    6615037.0
23    2017-08-16         64800.0          NaN    6550237.0
24    2017-08-16        141000.0          NaN    6409237.0
25    2017-08-16         61750.0          NaN    6347487.0
26    2017-08-16         67920.0          NaN    6279567.0
27    2017-08-16         78100.0          NaN    6201467.0
28    2017-08-16         35650.0          NaN    6165817.0
29    2017-08-16        206000.0          NaN    5959817.0
30    2017-08-16         35300.0          NaN    5924517.0
31    2017-08-16         49800.0          NaN    5874717.0
32    2017-08-16         53000.0          NaN    5821717.0
33    2017-08-16         91300.0          NaN    5730417.0
34    2017-08-16         57499.0          NaN    5672918.0
35    2017-08-16         20000.0          NaN    5652918.0
36    2017-08-16         19400.0          NaN    5633518.0
...          ...             ...          ...          ...
1004  2019-01-02        408376.0          NaN    1116408.0
1007  2019-01-03        826831.0          NaN     684417.0
1011  2019-01-04        601604.0          NaN     879573.0
1015  2019-01-05        218276.0          NaN    1359137.0
1017  2019-01-07         17500.0          NaN    1341397.0
1019  2019-01-07        377441.0          NaN     961196.0
1023  2019-01-08        613279.0          NaN     943957.0
1026  2019-01-09        674030.0          NaN     566207.0
1030  2019-01-10        293700.0          NaN    1070587.0
1033  2019-01-11        391453.0          NaN     976734.0
1037  2019-01-14        727659.0          NaN    1044515.0
1039  2019-01-14        344650.0          NaN     697345.0
1041  2019-01-14         50000.0          NaN     647105.0
1045  2019-01-15        473626.0          NaN     769879.0
1048  2019-01-16        108200.0          NaN     960719.0
1051  2019-01-17        446201.0          NaN    1011518.0
1054  2019-01-18        628628.0          NaN     779290.0
1057  2019-01-19        229800.0          NaN    1048050.0
1061  2019-01-21         98900.0          NaN    1548190.0
1063  2019-01-21         96200.0          NaN    1451510.0
1066  2019-01-22        602930.0          NaN    1144500.0
1069  2019-01-23        589137.0          NaN     951643.0
1072  2019-01-24        388327.0          NaN    1060436.0
1075  2019-01-25        245413.0          NaN    1312983.0
1078  2019-01-28        466124.0          NaN    1144939.0
1080  2019-01-28         17500.0          NaN    1127079.0
1083  2019-01-29        299125.0          NaN    1225434.0
1086  2019-01-30        401052.0          NaN    1121022.0
1088  2019-01-31        224051.0          NaN     895771.0
1091  2019-02-01        132851.0          NaN    1062200.0

[563 rows x 8 columns]

In [66]:
# bank_acc1 = bank[bank["Account No"] == 409000611074]

for i, (x, y) in enumerate(df_acc1.iterrows()):
#     print(df2.loc[i, "Account No"])
    if df_acc1.loc[i, "DEPOSIT AMT"] >= 0:
#         print(i)
        acc_no, date, deposit_amt, trans_details = df_acc1.loc[i, "Account No"], df_acc1.loc[i, "DATE"], df_acc1.loc[i, "DEPOSIT AMT"], df_acc1.loc[i, "TRANSACTION DETAILS"]
        
        df_temp =\
            df_acc1[(df_acc1["Account No"] == acc_no) & (df_acc1["DATE"] == date) & (df_acc1["WITHDRAWAL AMT"] >= 0)]
#         df_temp =\
#             df_acc1[(df_acc1["DATE"] == date) & (df_acc1["WITHDRAWAL AMT"] >= 0)]
    
        df_temp_res = seq_match(df_temp, trans_details)
        
#         if not df_temp_res.empty:
# #             print(f"Index - {i}")
#             print("xxxxxxxxxxxxxxxxxxxxxx")
# #             print(f"Row : {df_acc1.loc[i]}")            
#             print(df_temp_res)            
#             print("xxxxxxxxxxxxxxxxxxxxxx")
    
        if not df_temp.empty:
#             print(f"Index - {i}")
            print("xxxxxxxxxxxxxxxxxxxxxx")
#             print(f"Row : {df_acc1.loc[i]}")            
            print(df_temp)            
            print("xxxxxxxxxxxxxxxxxxxxxx")

xxxxxxxxxxxxxxxxxxxxxx
    level_0  index    Account No        DATE  \
0        10     10  409000611074  2017-08-16
1        11     11  409000611074  2017-08-16
2        12     12  409000611074  2017-08-16
3        13     13  409000611074  2017-08-16
4        14     14  409000611074  2017-08-16
5        15     15  409000611074  2017-08-16
6        16     16  409000611074  2017-08-16
7        17     17  409000611074  2017-08-16
8        18     18  409000611074  2017-08-16
9        19     19  409000611074  2017-08-16
10       20     20  409000611074  2017-08-16
11       21     21  409000611074  2017-08-16
12       22     22  409000611074  2017-08-16
13       23     23  409000611074  2017-08-16
14       24     24  409000611074  2017-08-16
15       25     25  409000611074  2017-08-16
16       26     26  409000611074  2017-08-16
17       27     27  409000611074  2017-08-16
18       28     28  409000611074  2017-08-16
19       29     29  409000611074  2017-08-16
20       30     30  409000611074  2017-08-16
21       31     31  409000611074  2017-08-16
22       32     32  409000611074  2017-08-16
23       33     33  409000611074  2017-08-16
24       34     34  409000611074  2017-08-16
25       35     35  409000611074  2017-08-16
26       36     36  409000611074  2017-08-16

                 TRANSACTION DETAILS  VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  \
0   INDO GIBL Indiaforensic STL01071  2017-08-16        133900.0          NaN
1   INDO GIBL Indiaforensic STL02071  2017-08-16         18000.0          NaN
2   INDO GIBL Indiaforensic STL03071  2017-08-16          5000.0          NaN
3   INDO GIBL Indiaforensic STL04071  2017-08-16        195800.0          NaN
4   INDO GIBL Indiaforensic STL05071  2017-08-16         81600.0          NaN
5   INDO GIBL Indiaforensic STL06071  2017-08-16         41800.0          NaN
6   INDO GIBL Indiaforensic STL07071  2017-08-16         98500.0          NaN
7   INDO GIBL Indiaforensic STL10071  2017-08-16        143800.0          NaN
8   INDO GIBL Indiaforensic STL11071  2017-08-16        331650.0          NaN
9   INDO GIBL Indiaforensic STL12071  2017-08-16        129000.0          NaN
10  INDO GIBL Indiaforensic STL13071  2017-08-16        230013.0          NaN
11  INDO GIBL Indiaforensic STL14071  2017-08-16        367900.0          NaN
12  INDO GIBL Indiaforensic STL15071  2017-08-16        108000.0          NaN
13  INDO GIBL Indiaforensic STL16071  2017-08-16         64800.0          NaN
14  INDO GIBL Indiaforensic STL17071  2017-08-16        141000.0          NaN
15  INDO GIBL Indiaforensic STL18071  2017-08-16         61750.0          NaN
16  INDO GIBL Indiaforensic STL19071  2017-08-16         67920.0          NaN
17  INDO GIBL Indiaforensic STL20071  2017-08-16         78100.0          NaN
18  INDO GIBL Indiaforensic STL21071  2017-08-16         35650.0          NaN
19  INDO GIBL Indiaforensic STL22071  2017-08-16        206000.0          NaN
20  INDO GIBL Indiaforensic STL24071  2017-08-16         35300.0          NaN
21  INDO GIBL Indiaforensic STL25071  2017-08-16         49800.0          NaN
22  INDO GIBL Indiaforensic STL26071  2017-08-16         53000.0          NaN
23  INDO GIBL Indiaforensic STL27071  2017-08-16         91300.0          NaN
24  INDO GIBL Indiaforensic STL28071  2017-08-16         57499.0          NaN
25  INDO GIBL Indiaforensic STL30071  2017-08-16         20000.0          NaN
26  INDO GIBL Indiaforensic STL31071  2017-08-16         19400.0          NaN

    BALANCE AMT
0     8366100.0
1     8348100.0
2     8343100.0
3     8147300.0
4     8065700.0
5     8023900.0
6     7925400.0
7     7781600.0
8     7449950.0
9     7320950.0
10    7090937.0
11    6723037.0
12    6615037.0
13    6550237.0
14    6409237.0
15    6347487.0
16    6279567.0
17    6201467.0
18    6165817.0
19    5959817.0
20    5924517.0
21    5874717.0
22    5821717.0
23    5730417.0
24    5672918.0
25    5652918.0
26    5633518.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
    level_0  index    Account No        DATE  \
0        10     10  409000611074  2017-08-16
1        11     11  409000611074  2017-08-16
2        12     12  409000611074  2017-08-16
3        13     13  409000611074  2017-08-16
4        14     14  409000611074  2017-08-16
5        15     15  409000611074  2017-08-16
6        16     16  409000611074  2017-08-16
7        17     17  409000611074  2017-08-16
8        18     18  409000611074  2017-08-16
9        19     19  409000611074  2017-08-16
10       20     20  409000611074  2017-08-16
11       21     21  409000611074  2017-08-16
12       22     22  409000611074  2017-08-16
13       23     23  409000611074  2017-08-16
14       24     24  409000611074  2017-08-16
15       25     25  409000611074  2017-08-16
16       26     26  409000611074  2017-08-16
17       27     27  409000611074  2017-08-16
18       28     28  409000611074  2017-08-16
19       29     29  409000611074  2017-08-16
20       30     30  409000611074  2017-08-16
21       31     31  409000611074  2017-08-16
22       32     32  409000611074  2017-08-16
23       33     33  409000611074  2017-08-16
24       34     34  409000611074  2017-08-16
25       35     35  409000611074  2017-08-16
26       36     36  409000611074  2017-08-16

                 TRANSACTION DETAILS  VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  \
0   INDO GIBL Indiaforensic STL01071  2017-08-16        133900.0          NaN
1   INDO GIBL Indiaforensic STL02071  2017-08-16         18000.0          NaN
2   INDO GIBL Indiaforensic STL03071  2017-08-16          5000.0          NaN
3   INDO GIBL Indiaforensic STL04071  2017-08-16        195800.0          NaN
4   INDO GIBL Indiaforensic STL05071  2017-08-16         81600.0          NaN
5   INDO GIBL Indiaforensic STL06071  2017-08-16         41800.0          NaN
6   INDO GIBL Indiaforensic STL07071  2017-08-16         98500.0          NaN
7   INDO GIBL Indiaforensic STL10071  2017-08-16        143800.0          NaN
8   INDO GIBL Indiaforensic STL11071  2017-08-16        331650.0          NaN
9   INDO GIBL Indiaforensic STL12071  2017-08-16        129000.0          NaN
10  INDO GIBL Indiaforensic STL13071  2017-08-16        230013.0          NaN
11  INDO GIBL Indiaforensic STL14071  2017-08-16        367900.0          NaN
12  INDO GIBL Indiaforensic STL15071  2017-08-16        108000.0          NaN
13  INDO GIBL Indiaforensic STL16071  2017-08-16         64800.0          NaN
14  INDO GIBL Indiaforensic STL17071  2017-08-16        141000.0          NaN
15  INDO GIBL Indiaforensic STL18071  2017-08-16         61750.0          NaN
16  INDO GIBL Indiaforensic STL19071  2017-08-16         67920.0          NaN
17  INDO GIBL Indiaforensic STL20071  2017-08-16         78100.0          NaN
18  INDO GIBL Indiaforensic STL21071  2017-08-16         35650.0          NaN
19  INDO GIBL Indiaforensic STL22071  2017-08-16        206000.0          NaN
20  INDO GIBL Indiaforensic STL24071  2017-08-16         35300.0          NaN
21  INDO GIBL Indiaforensic STL25071  2017-08-16         49800.0          NaN
22  INDO GIBL Indiaforensic STL26071  2017-08-16         53000.0          NaN
23  INDO GIBL Indiaforensic STL27071  2017-08-16         91300.0          NaN
24  INDO GIBL Indiaforensic STL28071  2017-08-16         57499.0          NaN
25  INDO GIBL Indiaforensic STL30071  2017-08-16         20000.0          NaN
26  INDO GIBL Indiaforensic STL31071  2017-08-16         19400.0          NaN

    BALANCE AMT
0     8366100.0
1     8348100.0
2     8343100.0
3     8147300.0
4     8065700.0
5     8023900.0
6     7925400.0
7     7781600.0
8     7449950.0
9     7320950.0
10    7090937.0
11    6723037.0
12    6615037.0
13    6550237.0
14    6409237.0
15    6347487.0
16    6279567.0
17    6201467.0
18    6165817.0
19    5959817.0
20    5924517.0
21    5874717.0
22    5821717.0
23    5730417.0
24    5672918.0
25    5652918.0
26    5633518.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
    level_0  index    Account No        DATE  \
0        10     10  409000611074  2017-08-16
1        11     11  409000611074  2017-08-16
2        12     12  409000611074  2017-08-16
3        13     13  409000611074  2017-08-16
4        14     14  409000611074  2017-08-16
5        15     15  409000611074  2017-08-16
6        16     16  409000611074  2017-08-16
7        17     17  409000611074  2017-08-16
8        18     18  409000611074  2017-08-16
9        19     19  409000611074  2017-08-16
10       20     20  409000611074  2017-08-16
11       21     21  409000611074  2017-08-16
12       22     22  409000611074  2017-08-16
13       23     23  409000611074  2017-08-16
14       24     24  409000611074  2017-08-16
15       25     25  409000611074  2017-08-16
16       26     26  409000611074  2017-08-16
17       27     27  409000611074  2017-08-16
18       28     28  409000611074  2017-08-16
19       29     29  409000611074  2017-08-16
20       30     30  409000611074  2017-08-16
21       31     31  409000611074  2017-08-16
22       32     32  409000611074  2017-08-16
23       33     33  409000611074  2017-08-16
24       34     34  409000611074  2017-08-16
25       35     35  409000611074  2017-08-16
26       36     36  409000611074  2017-08-16

                 TRANSACTION DETAILS  VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  \
0   INDO GIBL Indiaforensic STL01071  2017-08-16        133900.0          NaN
1   INDO GIBL Indiaforensic STL02071  2017-08-16         18000.0          NaN
2   INDO GIBL Indiaforensic STL03071  2017-08-16          5000.0          NaN
3   INDO GIBL Indiaforensic STL04071  2017-08-16        195800.0          NaN
4   INDO GIBL Indiaforensic STL05071  2017-08-16         81600.0          NaN
5   INDO GIBL Indiaforensic STL06071  2017-08-16         41800.0          NaN
6   INDO GIBL Indiaforensic STL07071  2017-08-16         98500.0          NaN
7   INDO GIBL Indiaforensic STL10071  2017-08-16        143800.0          NaN
8   INDO GIBL Indiaforensic STL11071  2017-08-16        331650.0          NaN
9   INDO GIBL Indiaforensic STL12071  2017-08-16        129000.0          NaN
10  INDO GIBL Indiaforensic STL13071  2017-08-16        230013.0          NaN
11  INDO GIBL Indiaforensic STL14071  2017-08-16        367900.0          NaN
12  INDO GIBL Indiaforensic STL15071  2017-08-16        108000.0          NaN
13  INDO GIBL Indiaforensic STL16071  2017-08-16         64800.0          NaN
14  INDO GIBL Indiaforensic STL17071  2017-08-16        141000.0          NaN
15  INDO GIBL Indiaforensic STL18071  2017-08-16         61750.0          NaN
16  INDO GIBL Indiaforensic STL19071  2017-08-16         67920.0          NaN
17  INDO GIBL Indiaforensic STL20071  2017-08-16         78100.0          NaN
18  INDO GIBL Indiaforensic STL21071  2017-08-16         35650.0          NaN
19  INDO GIBL Indiaforensic STL22071  2017-08-16        206000.0          NaN
20  INDO GIBL Indiaforensic STL24071  2017-08-16         35300.0          NaN
21  INDO GIBL Indiaforensic STL25071  2017-08-16         49800.0          NaN
22  INDO GIBL Indiaforensic STL26071  2017-08-16         53000.0          NaN
23  INDO GIBL Indiaforensic STL27071  2017-08-16         91300.0          NaN
24  INDO GIBL Indiaforensic STL28071  2017-08-16         57499.0          NaN
25  INDO GIBL Indiaforensic STL30071  2017-08-16         20000.0          NaN
26  INDO GIBL Indiaforensic STL31071  2017-08-16         19400.0          NaN

    BALANCE AMT
0     8366100.0
1     8348100.0
2     8343100.0
3     8147300.0
4     8065700.0
5     8023900.0
6     7925400.0
7     7781600.0
8     7449950.0
9     7320950.0
10    7090937.0
11    6723037.0
12    6615037.0
13    6550237.0
14    6409237.0
15    6347487.0
16    6279567.0
17    6201467.0
18    6165817.0
19    5959817.0
20    5924517.0
21    5874717.0
22    5821717.0
23    5730417.0
24    5672918.0
25    5652918.0
26    5633518.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
    level_0  index    Account No        DATE  \
0        10     10  409000611074  2017-08-16
1        11     11  409000611074  2017-08-16
2        12     12  409000611074  2017-08-16
3        13     13  409000611074  2017-08-16
4        14     14  409000611074  2017-08-16
5        15     15  409000611074  2017-08-16
6        16     16  409000611074  2017-08-16
7        17     17  409000611074  2017-08-16
8        18     18  409000611074  2017-08-16
9        19     19  409000611074  2017-08-16
10       20     20  409000611074  2017-08-16
11       21     21  409000611074  2017-08-16
12       22     22  409000611074  2017-08-16
13       23     23  409000611074  2017-08-16
14       24     24  409000611074  2017-08-16
15       25     25  409000611074  2017-08-16
16       26     26  409000611074  2017-08-16
17       27     27  409000611074  2017-08-16
18       28     28  409000611074  2017-08-16
19       29     29  409000611074  2017-08-16
20       30     30  409000611074  2017-08-16
21       31     31  409000611074  2017-08-16
22       32     32  409000611074  2017-08-16
23       33     33  409000611074  2017-08-16
24       34     34  409000611074  2017-08-16
25       35     35  409000611074  2017-08-16
26       36     36  409000611074  2017-08-16

                 TRANSACTION DETAILS  VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  \
0   INDO GIBL Indiaforensic STL01071  2017-08-16        133900.0          NaN
1   INDO GIBL Indiaforensic STL02071  2017-08-16         18000.0          NaN
2   INDO GIBL Indiaforensic STL03071  2017-08-16          5000.0          NaN
3   INDO GIBL Indiaforensic STL04071  2017-08-16        195800.0          NaN
4   INDO GIBL Indiaforensic STL05071  2017-08-16         81600.0          NaN
5   INDO GIBL Indiaforensic STL06071  2017-08-16         41800.0          NaN
6   INDO GIBL Indiaforensic STL07071  2017-08-16         98500.0          NaN
7   INDO GIBL Indiaforensic STL10071  2017-08-16        143800.0          NaN
8   INDO GIBL Indiaforensic STL11071  2017-08-16        331650.0          NaN
9   INDO GIBL Indiaforensic STL12071  2017-08-16        129000.0          NaN
10  INDO GIBL Indiaforensic STL13071  2017-08-16        230013.0          NaN
11  INDO GIBL Indiaforensic STL14071  2017-08-16        367900.0          NaN
12  INDO GIBL Indiaforensic STL15071  2017-08-16        108000.0          NaN
13  INDO GIBL Indiaforensic STL16071  2017-08-16         64800.0          NaN
14  INDO GIBL Indiaforensic STL17071  2017-08-16        141000.0          NaN
15  INDO GIBL Indiaforensic STL18071  2017-08-16         61750.0          NaN
16  INDO GIBL Indiaforensic STL19071  2017-08-16         67920.0          NaN
17  INDO GIBL Indiaforensic STL20071  2017-08-16         78100.0          NaN
18  INDO GIBL Indiaforensic STL21071  2017-08-16         35650.0          NaN
19  INDO GIBL Indiaforensic STL22071  2017-08-16        206000.0          NaN
20  INDO GIBL Indiaforensic STL24071  2017-08-16         35300.0          NaN
21  INDO GIBL Indiaforensic STL25071  2017-08-16         49800.0          NaN
22  INDO GIBL Indiaforensic STL26071  2017-08-16         53000.0          NaN
23  INDO GIBL Indiaforensic STL27071  2017-08-16         91300.0          NaN
24  INDO GIBL Indiaforensic STL28071  2017-08-16         57499.0          NaN
25  INDO GIBL Indiaforensic STL30071  2017-08-16         20000.0          NaN
26  INDO GIBL Indiaforensic STL31071  2017-08-16         19400.0          NaN

    BALANCE AMT
0     8366100.0
1     8348100.0
2     8343100.0
3     8147300.0
4     8065700.0
5     8023900.0
6     7925400.0
7     7781600.0
8     7449950.0
9     7320950.0
10    7090937.0
11    6723037.0
12    6615037.0
13    6550237.0
14    6409237.0
15    6347487.0
16    6279567.0
17    6201467.0
18    6165817.0
19    5959817.0
20    5924517.0
21    5874717.0
22    5821717.0
23    5730417.0
24    5672918.0
25    5652918.0
26    5633518.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
    level_0  index    Account No        DATE  \
0        10     10  409000611074  2017-08-16
1        11     11  409000611074  2017-08-16
2        12     12  409000611074  2017-08-16
3        13     13  409000611074  2017-08-16
4        14     14  409000611074  2017-08-16
5        15     15  409000611074  2017-08-16
6        16     16  409000611074  2017-08-16
7        17     17  409000611074  2017-08-16
8        18     18  409000611074  2017-08-16
9        19     19  409000611074  2017-08-16
10       20     20  409000611074  2017-08-16
11       21     21  409000611074  2017-08-16
12       22     22  409000611074  2017-08-16
13       23     23  409000611074  2017-08-16
14       24     24  409000611074  2017-08-16
15       25     25  409000611074  2017-08-16
16       26     26  409000611074  2017-08-16
17       27     27  409000611074  2017-08-16
18       28     28  409000611074  2017-08-16
19       29     29  409000611074  2017-08-16
20       30     30  409000611074  2017-08-16
21       31     31  409000611074  2017-08-16
22       32     32  409000611074  2017-08-16
23       33     33  409000611074  2017-08-16
24       34     34  409000611074  2017-08-16
25       35     35  409000611074  2017-08-16
26       36     36  409000611074  2017-08-16

                 TRANSACTION DETAILS  VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  \
0   INDO GIBL Indiaforensic STL01071  2017-08-16        133900.0          NaN
1   INDO GIBL Indiaforensic STL02071  2017-08-16         18000.0          NaN
2   INDO GIBL Indiaforensic STL03071  2017-08-16          5000.0          NaN
3   INDO GIBL Indiaforensic STL04071  2017-08-16        195800.0          NaN
4   INDO GIBL Indiaforensic STL05071  2017-08-16         81600.0          NaN
5   INDO GIBL Indiaforensic STL06071  2017-08-16         41800.0          NaN
6   INDO GIBL Indiaforensic STL07071  2017-08-16         98500.0          NaN
7   INDO GIBL Indiaforensic STL10071  2017-08-16        143800.0          NaN
8   INDO GIBL Indiaforensic STL11071  2017-08-16        331650.0          NaN
9   INDO GIBL Indiaforensic STL12071  2017-08-16        129000.0          NaN
10  INDO GIBL Indiaforensic STL13071  2017-08-16        230013.0          NaN
11  INDO GIBL Indiaforensic STL14071  2017-08-16        367900.0          NaN
12  INDO GIBL Indiaforensic STL15071  2017-08-16        108000.0          NaN
13  INDO GIBL Indiaforensic STL16071  2017-08-16         64800.0          NaN
14  INDO GIBL Indiaforensic STL17071  2017-08-16        141000.0          NaN
15  INDO GIBL Indiaforensic STL18071  2017-08-16         61750.0          NaN
16  INDO GIBL Indiaforensic STL19071  2017-08-16         67920.0          NaN
17  INDO GIBL Indiaforensic STL20071  2017-08-16         78100.0          NaN
18  INDO GIBL Indiaforensic STL21071  2017-08-16         35650.0          NaN
19  INDO GIBL Indiaforensic STL22071  2017-08-16        206000.0          NaN
20  INDO GIBL Indiaforensic STL24071  2017-08-16         35300.0          NaN
21  INDO GIBL Indiaforensic STL25071  2017-08-16         49800.0          NaN
22  INDO GIBL Indiaforensic STL26071  2017-08-16         53000.0          NaN
23  INDO GIBL Indiaforensic STL27071  2017-08-16         91300.0          NaN
24  INDO GIBL Indiaforensic STL28071  2017-08-16         57499.0          NaN
25  INDO GIBL Indiaforensic STL30071  2017-08-16         20000.0          NaN
26  INDO GIBL Indiaforensic STL31071  2017-08-16         19400.0          NaN

    BALANCE AMT
0     8366100.0
1     8348100.0
2     8343100.0
3     8147300.0
4     8065700.0
5     8023900.0
6     7925400.0
7     7781600.0
8     7449950.0
9     7320950.0
10    7090937.0
11    6723037.0
12    6615037.0
13    6550237.0
14    6409237.0
15    6347487.0
16    6279567.0
17    6201467.0
18    6165817.0
19    5959817.0
20    5924517.0
21    5874717.0
22    5821717.0
23    5730417.0
24    5672918.0
25    5652918.0
26    5633518.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
    level_0  index    Account No        DATE  \
0        10     10  409000611074  2017-08-16
1        11     11  409000611074  2017-08-16
2        12     12  409000611074  2017-08-16
3        13     13  409000611074  2017-08-16

xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      151    151  409000611074  2017-11-17  INDO GIBL Indiaforensic STL16111
1      152    152  409000611074  2017-11-17  INDO GIBL Indiaforensic STL15111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-11-17         94900.0          NaN    1166926.0
1  2017-11-17        224851.0          NaN     942075.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      151    151  409000611074  2017-11-17  INDO GIBL Indiaforensic STL16111
1      152    152  409000611074  2017-11-17  INDO GIBL Indiaforensic STL15111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-11-17         94900.0          NaN    1166926.0
1  2017-11-17        224851.0          NaN     942075.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      157    157  409000611074  2017-11-21  INDO GIBL Indiaforensic STL20111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-11-21        145900.0          NaN     856072.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      162    162  409000611074  2017-11-27  INDO GIBL Indiaforensic STL24117
1      163    163  409000611074  2017-11-27  INDO GIBL Indiaforensic STL25117
2      164    164  409000611074  2017-11-27  INDO GIBL Indiaforensic STL26117

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-11-27         19400.0          NaN     986422.0
1  2017-11-27         39700.0          NaN     946722.0
2  2017-11-27         42800.0          NaN     903922.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      174    174  409000611074  2017-12-06  INDO GIBL Indiaforensic STL05121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-06        218050.0          NaN     783159.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      188    188  409000611074  2017-12-18  INDO GIBL Indiaforensic STL15121
1      189    189  409000611074  2017-12-18  INDO GIBL Indiaforensic STL17121
2      190    190  409000611074  2017-12-18  INDO GIBL Indiaforensic STL16121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-18        210500.0          NaN     927855.0
1  2017-12-18        139500.0          NaN     788355.0
2  2017-12-18         92550.0          NaN     695805.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      188    188  409000611074  2017-12-18  INDO GIBL Indiaforensic STL15121
1      189    189  409000611074  2017-12-18  INDO GIBL Indiaforensic STL17121
2      190    190  409000611074  2017-12-18  INDO GIBL Indiaforensic STL16121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-18        210500.0          NaN     927855.0
1  2017-12-18        139500.0          NaN     788355.0
2  2017-12-18         92550.0          NaN     695805.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      193    193  409000611074  2017-12-19  INDO GIBL Indiaforensic STL18121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-19        654498.0          NaN    1041307.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      193    193  409000611074  2017-12-19  INDO GIBL Indiaforensic STL18121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-19        654498.0          NaN    1041307.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      194    194  409000611074  2017-12-20  INDO GIBL Indiaforensic STL19121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-20        504450.0          NaN     536857.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      196    196  409000611074  2017-12-21  INDO GIBL Indiaforensic STL20121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-21        561225.0          NaN     475632.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      196    196  409000611074  2017-12-21  INDO GIBL Indiaforensic STL20121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-21        561225.0          NaN     475632.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      205    205  409000611074  2017-12-27  INDO GIBL Indiaforensic STL26121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-27        259525.0          NaN    1018482.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      207    207  409000611074  2017-12-29  INDO GIBL Indiaforensic STL28121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2017-12-29        138150.0          NaN     497222.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      214    214  409000611074  2018-01-03  INDO GIBL Indiaforensic STL02011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-01-03        323500.0          NaN     672573.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      218    218  409000611074  2018-01-05  INDO GIBL Indiaforensic STL04011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-01-05        222800.0          NaN    1269473.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      218    218  409000611074  2018-01-05  INDO GIBL Indiaforensic STL04011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-01-05        222800.0          NaN    1269473.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      220    220  409000611074  2018-01-09  INDO GIBL Indiaforensic STL06011
1      221    221  409000611074  2018-01-09  INDO GIBL Indiaforensic STL07011
2      222    222  409000611074  2018-01-09  INDO GIBL Indiaforensic STL08011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-01-09        182000.0          NaN     942023.0
1  2018-01-09        205075.0          NaN     736948.0
2  2018-01-09        170500.0          NaN     566448.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      247    247  409000611074  2018-01-29  INDO GIBL Indiaforensic STL25011
1      248    248  409000611074  2018-01-29  INDO GIBL Indiaforensic STL26011
2      249    249  409000611074  2018-01-29  INDO GIBL Indiaforensic STL27011
3      250    250  409000611074  2018-01-29  INDO GIBL Indiaforensic STL28011
4      251    251  409000611074  2018-01-29  INDO GIBL Indiaforensic STL24011
5      252    252  409000611074  2018-01-29  INDO GIBL Indiaforensic STL17011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-01-29        135050.0          NaN    1621595.0
1  2018-01-29         31300.0          NaN    1590295.0
2  2018-01-29         20500.0          NaN    1569795.0
3  2018-01-29          5500.0          NaN    1564295.0
4  2018-01-29        204900.0          NaN    1359395.0
5  2018-01-29        563250.0          NaN     796145.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      247    247  409000611074  2018-01-29  INDO GIBL Indiaforensic STL25011
1      248    248  409000611074  2018-01-29  INDO GIBL Indiaforensic STL26011
2      249    249  409000611074  2018-01-29  INDO GIBL Indiaforensic STL27011
3      250    250  409000611074  2018-01-29  INDO GIBL Indiaforensic STL28011
4      251    251  409000611074  2018-01-29  INDO GIBL Indiaforensic STL24011
5      252    252  409000611074  2018-01-29  INDO GIBL Indiaforensic STL17011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-01-29        135050.0          NaN    1621595.0
1  2018-01-29         31300.0          NaN    1590295.0
2  2018-01-29         20500.0          NaN    1569795.0
3  2018-01-29          5500.0          NaN    1564295.0
4  2018-01-29        204900.0          NaN    1359395.0
5  2018-01-29        563250.0          NaN     796145.0
xxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      247    247  409000611074  2018-01-29  INDO GIBL Indiaforensic STL25011
1      248    248  409000611074  2018-01-29  INDO GIBL Indiaforensic STL26011
2      249    249  409000611074  2018-01-29  INDO GIBL Indiaforensic STL27011
3      250    250  409000611074  2018-01-29  INDO GIBL Indiaforensic STL28011
4      251    251  409000611074  2018-01-29  INDO GIBL Indiaforensic STL24011
5      252    252  409000611074  2018-01-29  INDO GIBL Indiaforensic STL17011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-01-29        135050.0          NaN    1621595.0
1  2018-01-29         31300.0          NaN    1590295.0
2  2018-01-29         20500.0          NaN    1569795.0
3  2018-01-29          5500.0          NaN    1564295.0
4  2018-01-29        204900.0          NaN    1359395.0
5  2018-01-29        563250.0          NaN     796145.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      268    268  409000611074  2018-02-16  INDO GIBL Indiaforensic STL09021
1      269    269  409000611074  2018-02-16  INDO GIBL Indiaforensic STL10021
2      270    270  409000611074  2018-02-16  INDO GIBL Indiaforensic STL13021
3      271    271  409000611074  2018-02-16  INDO GIBL Indiaforensic STL14021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-16        334900.0          NaN    1151122.0
1  2018-02-16         68250.0          NaN    1082872.0
2  2018-02-16        307125.0          NaN     775747.0
3  2018-02-16        475300.0          NaN     300447.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      268    268  409000611074  2018-02-16  INDO GIBL Indiaforensic STL09021
1      269    269  409000611074  2018-02-16  INDO GIBL Indiaforensic STL10021
2      270    270  409000611074  2018-02-16  INDO GIBL Indiaforensic STL13021
3      271    271  409000611074  2018-02-16  INDO GIBL Indiaforensic STL14021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-16        334900.0          NaN    1151122.0
1  2018-02-16         68250.0          NaN    1082872.0
2  2018-02-16        307125.0          NaN     775747.0
3  2018-02-16        475300.0          NaN     300447.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      268    268  409000611074  2018-02-16  INDO GIBL Indiaforensic STL09021
1      269    269  409000611074  2018-02-16  INDO GIBL Indiaforensic STL10021
2      270    270  409000611074  2018-02-16  INDO GIBL Indiaforensic STL13021
3      271    271  409000611074  2018-02-16  INDO GIBL Indiaforensic STL14021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-16        334900.0          NaN    1151122.0
1  2018-02-16         68250.0          NaN    1082872.0
2  2018-02-16        307125.0          NaN     775747.0
3  2018-02-16        475300.0          NaN     300447.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      282    282  409000611074  2018-02-22  INDO GIBL Indiaforensic STL18021
1      283    283  409000611074  2018-02-22  INDO GIBL Indiaforensic STL19021
2      284    284  409000611074  2018-02-22  INDO GIBL Indiaforensic STL20021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-22         79350.0          NaN    1143469.0
1  2018-02-22        385200.0          NaN     758269.0
2  2018-02-22        299950.0          NaN     458319.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      282    282  409000611074  2018-02-22  INDO GIBL Indiaforensic STL18021
1      283    283  409000611074  2018-02-22  INDO GIBL Indiaforensic STL19021
2      284    284  409000611074  2018-02-22  INDO GIBL Indiaforensic STL20021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-22         79350.0          NaN    1143469.0
1  2018-02-22        385200.0          NaN     758269.0
2  2018-02-22        299950.0          NaN     458319.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      282    282  409000611074  2018-02-22  INDO GIBL Indiaforensic STL18021
1      283    283  409000611074  2018-02-22  INDO GIBL Indiaforensic STL19021
2      284    284  409000611074  2018-02-22  INDO GIBL Indiaforensic STL20021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-22         79350.0          NaN    1143469.0
1  2018-02-22        385200.0          NaN     758269.0
2  2018-02-22        299950.0          NaN     458319.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      287    287  409000611074  2018-02-26  INDO GIBL Indiaforensic STL21021
1      288    288  409000611074  2018-02-26  INDO GIBL Indiaforensic STL22021
2      289    289  409000611074  2018-02-26  INDO GIBL Indiaforensic STL23021
3      290    290  409000611074  2018-02-26  INDO GIBL Indiaforensic STL24021
4      291    291  409000611074  2018-02-26  INDO GIBL Indiaforensic STL25021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-26        273500.0          NaN    1184819.0
1  2018-02-26        237500.0          NaN     947319.0
2  2018-02-26        277753.0          NaN     669566.0
3  2018-02-26         70300.0          NaN     599266.0
4  2018-02-26         62400.0          NaN     536866.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      287    287  409000611074  2018-02-26  INDO GIBL Indiaforensic STL21021
1      288    288  409000611074  2018-02-26  INDO GIBL Indiaforensic STL22021
2      289    289  409000611074  2018-02-26  INDO GIBL Indiaforensic STL23021
3      290    290  409000611074  2018-02-26  INDO GIBL Indiaforensic STL24021
4      291    291  409000611074  2018-02-26  INDO GIBL Indiaforensic STL25021

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-02-26        273500.0          NaN    1184819.0
1  2018-02-26        237500.0          NaN     947319.0
2  2018-02-26        277753.0          NaN     669566.0
3  2018-02-26         70300.0          NaN     599266.0
4  2018-02-26         62400.0          NaN     536866.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      305    305  409000611074  2018-03-09  INDO GIBL Indiaforensic STL08031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-09        345930.0          NaN     271687.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      305    305  409000611074  2018-03-09  INDO GIBL Indiaforensic STL08031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-09        345930.0          NaN     271687.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      308    308  409000611074  2018-03-12  INDO GIBL Indiaforensic STL09031
1      309    309  409000611074  2018-03-12   INDO GIBL Indiaforensic STL1003
2      310    310  409000611074  2018-03-12  INDO GIBL Indiaforensic STL11031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-12        390850.0          NaN     880837.0
1  2018-03-12         85800.0          NaN     795037.0
2  2018-03-12         45000.0          NaN     750037.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      308    308  409000611074  2018-03-12  INDO GIBL Indiaforensic STL09031
1      309    309  409000611074  2018-03-12   INDO GIBL Indiaforensic STL1003
2      310    310  409000611074  2018-03-12  INDO GIBL Indiaforensic STL11031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-12        390850.0          NaN     880837.0
1  2018-03-12         85800.0          NaN     795037.0
2  2018-03-12         45000.0          NaN     750037.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      314    314  409000611074  2018-03-14  INDO GIBL Indiaforensic STL13031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-14        556224.0          NaN     616320.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      314    314  409000611074  2018-03-14  INDO GIBL Indiaforensic STL13031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-14        556224.0          NaN     616320.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      318    318  409000611074  2018-03-16  INDO GIBL Indiaforensic STL15031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-16        213463.0          NaN     977157.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      323    323  409000611074  2018-03-20  INDO GIBL Indiaforensic STL19031
1      328    328  409000611074  2018-03-20  INDO GIBL Indiaforensic STL01031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-20        335250.0          NaN     701414.0
1  2018-03-20        200799.0          NaN    1360234.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      323    323  409000611074  2018-03-20  INDO GIBL Indiaforensic STL19031
1      328    328  409000611074  2018-03-20  INDO GIBL Indiaforensic STL01031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-20        335250.0          NaN     701414.0
1  2018-03-20        200799.0          NaN    1360234.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      323    323  409000611074  2018-03-20  INDO GIBL Indiaforensic STL19031
1      328    328  409000611074  2018-03-20  INDO GIBL Indiaforensic STL01031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-20        335250.0          NaN     701414.0
1  2018-03-20        200799.0          NaN    1360234.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      323    323  409000611074  2018-03-20  INDO GIBL Indiaforensic STL19031
1      328    328  409000611074  2018-03-20  INDO GIBL Indiaforensic STL01031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-20        335250.0          NaN     701414.0
1  2018-03-20        200799.0          NaN    1360234.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      329    329  409000611074  2018-03-22  INDO GIBL Indiaforensic STL20031
1      330    330  409000611074  2018-03-22  INDO GIBL Indiaforensic STL21031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-22        434450.0          NaN     925784.0
1  2018-03-22        292175.0          NaN     633609.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      329    329  409000611074  2018-03-22  INDO GIBL Indiaforensic STL20031
1      330    330  409000611074  2018-03-22  INDO GIBL Indiaforensic STL21031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-22        434450.0          NaN     925784.0
1  2018-03-22        292175.0          NaN     633609.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      333    333  409000611074  2018-03-23  INDO GIBL Indiaforensic STL22031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-23        301200.0          NaN    1332409.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      340    340  409000611074  2018-03-31  INDO GIBL Indiaforensic STL28031
1      341    341  409000611074  2018-03-31  INDO GIBL Indiaforensic STL29031
2      342    342  409000611074  2018-03-31  INDO GIBL Indiaforensic STL30031

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-03-31        164600.0          NaN     993234.0
1  2018-03-31         81675.0          NaN     911559.0
2  2018-03-31         85750.0          NaN     825809.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      353    353  409000611074  2018-04-09  INDO GIBL Indiaforensic STL07041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-09         48800.0          NaN    1039109.0
xxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      357    357  409000611074  2018-04-11  INDO GIBL Indiaforensic STL10041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-11        162600.0          NaN    1570559.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      358    358  409000611074  2018-04-12  INDO GIBL Indiaforensic STL11041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-12        639700.0          NaN     930859.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      360    360  409000611074  2018-04-13  INDO GIBL Indiaforensic STL12041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-13        363900.0          NaN    1066959.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      360    360  409000611074  2018-04-13  INDO GIBL Indiaforensic STL12041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-13        363900.0          NaN    1066959.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      368    368  409000611074  2018-04-18  INDO GIBL Indiaforensic STL17041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-18        574150.0          NaN     964309.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      369    369  409000611074  2018-04-19  INDO GIBL Indiaforensic STL18041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-19        388550.0          NaN     575759.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      372    372  409000611074  2018-04-21  INDO GIBL Indiaforensic STL20041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-21        167591.0          NaN     631868.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      372    372  409000611074  2018-04-21  INDO GIBL Indiaforensic STL20041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-21        167591.0          NaN     631868.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      381    381  409000611074  2018-04-27  INDO GIBL Indiaforensic STL25041
1      382    382  409000611074  2018-04-27  INDO GIBL Indiaforensic STL26041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-04-27        414276.0          NaN    1188942.0
1  2018-04-27        351100.0          NaN     837842.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      385    385  409000611074  2018-05-02  INDO GIBL Indiaforensic STL27041
1      386    386  409000611074  2018-05-02  INDO GIBL Indiaforensic STL28041
2      387    387  409000611074  2018-05-02  INDO GIBL Indiaforensic STL29041
3      388    388  409000611074  2018-05-02  INDO GIBL Indiaforensic STL30041
4      389    389  409000611074  2018-05-02  INDO GIBL Indiaforensic STL01051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-02        229949.0          NaN    1607893.0
1  2018-05-02        160300.0          NaN    1447593.0
2  2018-05-02         76000.0          NaN    1371593.0
3  2018-05-02         60449.0          NaN    1311144.0
4  2018-05-02        259075.0          NaN    1052069.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      391    391  409000611074  2018-05-03  INDO GIBL Indiaforensic STL02051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-03        206700.0          NaN    1345369.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      395    395  409000611074  2018-05-07  INDO GIBL Indiaforensic STL05051
1      396    396  409000611074  2018-05-07  INDO GIBL Indiaforensic STL06051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-07        387749.0          NaN     948620.0
1  2018-05-07        101050.0          NaN     847570.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      399    399  409000611074  2018-05-09  INDO GIBL Indiaforensic STL08051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-09        290350.0          NaN     664320.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      399    399  409000611074  2018-05-09  INDO GIBL Indiaforensic STL08051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-09        290350.0          NaN     664320.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      403    403  409000611074  2018-05-11  INDO GIBL Indiaforensic STL10051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-11        352850.0          NaN     945845.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      405    405  409000611074  2018-05-14  INDO GIBL Indiaforensic STL11051
1      406    406  409000611074  2018-05-14  INDO GIBL Indiaforensic STL12051
2      407    407  409000611074  2018-05-14  INDO GIBL Indiaforensic STL13051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-14        345749.0          NaN    1100096.0
1  2018-05-14        225300.0          NaN     874796.0
2  2018-05-14         10000.0          NaN     864796.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      409    409  409000611074  2018-05-15  INDO GIBL Indiaforensic STL14051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-15        823240.0          NaN     541556.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      409    409  409000611074  2018-05-15  INDO GIBL Indiaforensic STL14051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-15        823240.0          NaN     541556.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      414    414  409000611074  2018-05-17  INDO GIBL Indiaforensic STL16051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-17        403100.0          NaN     853407.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      414    414  409000611074  2018-05-17  INDO GIBL Indiaforensic STL16051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-17        403100.0          NaN     853407.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      416    416  409000611074  2018-05-18  INDO GIBL Indiaforensic STL17051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-18        459800.0          NaN     893607.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      419    419  409000611074  2018-05-21  INDO GIBL Indiaforensic STL19051
1      420    420  409000611074  2018-05-21  INDO GIBL Indiaforensic STL20051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-21        265500.0          NaN     754257.0
1  2018-05-21         25700.0          NaN     728557.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      422    422  409000611074  2018-05-22  INDO GIBL Indiaforensic STL21051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-22        376125.0          NaN     852432.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      425    425  409000611074  2018-05-24  INDO GIBL Indiaforensic STL23051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-24        119100.0          NaN     968082.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      428    428  409000611074  2018-05-28  INDO GIBL Indiaforensic STL25051
1      429    429  409000611074  2018-05-28  INDO GIBL Indiaforensic STL26051
2      430    430  409000611074  2018-05-28  INDO GIBL Indiaforensic STL27051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-28        201000.0          NaN    1173732.0
1  2018-05-28         80475.0          NaN    1093257.0
2  2018-05-28         27200.0          NaN    1066057.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      433    433  409000611074  2018-05-30  INDO GIBL Indiaforensic STL29051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-05-30        341200.0          NaN     860757.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      437    437  409000611074  2018-06-01  INDO GIBL Indiaforensic STL31051

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT

0  2018-06-01         78000.0          NaN    1548157.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      440    440  409000611074  2018-06-04  INDO GIBL Indiaforensic STL02061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-04        402850.0          NaN    1291807.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      442    442  409000611074  2018-06-06  INDO GIBL Indiaforensic STL05061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-06        251200.0          NaN     461857.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      442    442  409000611074  2018-06-06  INDO GIBL Indiaforensic STL05061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-06        251200.0          NaN     461857.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      449    449  409000611074  2018-06-11  INDO GIBL Indiaforensic STL08061
1      450    450  409000611074  2018-06-11  INDO GIBL Indiaforensic STL09061
2      451    451  409000611074  2018-06-11  INDO GIBL Indiaforensic STL10061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-11        626600.0          NaN    1127177.0
1  2018-06-11        340074.0          NaN     787103.0
2  2018-06-11         24176.0          NaN     762927.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      449    449  409000611074  2018-06-11  INDO GIBL Indiaforensic STL08061
1      450    450  409000611074  2018-06-11  INDO GIBL Indiaforensic STL09061
2      451    451  409000611074  2018-06-11  INDO GIBL Indiaforensic STL10061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-11        626600.0          NaN    1127177.0
1  2018-06-11        340074.0          NaN     787103.0
2  2018-06-11         24176.0          NaN     762927.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      454    454  409000611074  2018-06-12  INDO GIBL Indiaforensic STL11061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-12        793251.0          NaN     969676.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      454    454  409000611074  2018-06-12  INDO GIBL Indiaforensic STL11061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-12        793251.0          NaN     969676.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      456    456  409000611074  2018-06-13  INDO GIBL Indiaforensic STL12061
1      457    457  409000611074  2018-06-13  INDO GIBL Indiaforensic STL27041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-13        717850.0          NaN     751826.0
1  2018-06-13         32000.0          NaN     719826.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      456    456  409000611074  2018-06-13  INDO GIBL Indiaforensic STL12061
1      457    457  409000611074  2018-06-13  INDO GIBL Indiaforensic STL27041

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-13        717850.0          NaN     751826.0
1  2018-06-13         32000.0          NaN     719826.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      460    460  409000611074  2018-06-14  INDO GIBL Indiaforensic STL13061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-14        533800.0          NaN    1686026.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      461    461  409000611074  2018-06-15  INDO GIBL Indiaforensic STL14061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-15        559730.0          NaN    1126296.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      467    467  409000611074  2018-06-19  INDO GIBL Indiaforensic STL18061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-19        709200.0          NaN    1398896.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      469    469  409000611074  2018-06-20  INDO GIBL Indiaforensic STL19061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-20        689650.0          NaN    1209246.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      471    471  409000611074  2018-06-21  INDO GIBL Indiaforensic STL20061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-21        386200.0          NaN    1323046.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      472    472  409000611074  2018-06-22  INDO GIBL Indiaforensic STL21061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-22        434905.0          NaN     888141.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      474    474  409000611074  2018-06-25  INDO GIBL Indiaforensic STL24061
1      475    475  409000611074  2018-06-25  INDO GIBL Indiaforensic STL23061
2      476    476  409000611074  2018-06-25  INDO GIBL Indiaforensic STL22061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-25          6050.0          NaN    1882091.0
1  2018-06-25        115051.0          NaN    1767040.0
2  2018-06-25        242750.0          NaN    1524290.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE        TRANSACTION DETAILS  \
0      481    481  409000611074  2018-06-28  GIBLRBL INC INDO REM27061
1      482    482  409000611074  2018-06-28         INDO MFL STL270618

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-28          2640.0          NaN    1732037.0
1  2018-06-28        344750.0          NaN    1387287.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      483    483  409000611074  2018-06-29      Indfor INCOME INDO REMI28061
1      484    484  409000611074  2018-06-29  INDO GIBL Indiaforensic STL28061

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-06-29          2160.0          NaN    1385127.0
1  2018-06-29        410181.0          NaN     974946.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      489    489  409000611074  2018-07-02      Indfor INCOME INDO REMI30061
1      490    490  409000611074  2018-07-02  INDO GIBL Indiaforensic STL30061
2      491    491  409000611074  2018-07-02      Indfor INCOME INDO REMI01071
3      492    492  409000611074  2018-07-02  INDO GIBL Indiaforensic STL01071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-02           960.0          NaN    1796616.0
1  2018-07-02        200250.0          NaN    1596366.0
2  2018-07-02           120.0          NaN    1596246.0
3  2018-07-02         10000.0          NaN    1586246.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      493    493  409000611074  2018-07-04      Indfor INCOME INDO REMI02071
1      494    494  409000611074  2018-07-04  INDO GIBL Indiaforensic STL02071
2      496    496  409000611074  2018-07-04      Indfor INCOME INDO REMI03071
3      497    497  409000611074  2018-07-04  INDO GIBL Indiaforensic STL03071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-04          2280.0          NaN    1583966.0
1  2018-07-04        282208.0          NaN    1301758.0
2  2018-07-04          2280.0          NaN    1799478.0
3  2018-07-04        323700.0          NaN    1475778.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      500    500  409000611074  2018-07-06      Indfor INCOME INDO REMI05071
1      501    501  409000611074  2018-07-06  INDO GIBL Indiaforensic STL05071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-06          2520.0          NaN     941118.0
1  2018-07-06        431899.0          NaN     509219.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      503    503  409000611074  2018-07-07      Indfor INCOME INDO REMI06071
1      504    504  409000611074  2018-07-07  INDO GIBL Indiaforensic STL06071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-07          2640.0          NaN    1006579.0
1  2018-07-07        295000.0          NaN     711579.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      506    506  409000611074  2018-07-09      Indfor INCOME INDO REMI08071
1      507    507  409000611074  2018-07-09  INDO GIBL Indiaforensic STL08071
2      508    508  409000611074  2018-07-09      Indfor INCOME INDO REMI07071
3      509    509  409000611074  2018-07-09  INDO GIBL Indiaforensic STL07071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-09           120.0          NaN    1211459.0
1  2018-07-09         30700.0          NaN    1180759.0
2  2018-07-09          1200.0          NaN    1179559.0
3  2018-07-09        213225.0          NaN     966334.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      511    511  409000611074  2018-07-10      Indfor INCOME INDO REMI09071
1      512    512  409000611074  2018-07-10  INDO GIBL Indiaforensic STL09071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-10          4800.0          NaN    1461534.0
1  2018-07-10        809926.0          NaN     651608.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      514    514  409000611074  2018-07-11      Indfor INCOME INDO REMI10071
1      515    515  409000611074  2018-07-11  INDO GIBL Indiaforensic STL10071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-11          2640.0          NaN    1148968.0
1  2018-07-11        435225.0          NaN     713743.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      518    518  409000611074  2018-07-12      Indfor INCOME INDO REMI11071
1      519    519  409000611074  2018-07-12  INDO GIBL Indiaforensic STL11071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-12          4560.0          NaN    1709183.0
1  2018-07-12        828988.0          NaN     880195.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      518    518  409000611074  2018-07-12      Indfor INCOME INDO REMI11071
1      519    519  409000611074  2018-07-12  INDO GIBL Indiaforensic STL11071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-12          4560.0          NaN    1709183.0
1  2018-07-12        828988.0          NaN     880195.0
xxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      521    521  409000611074  2018-07-13      Indfor INCOME INDO REMI12071
1      522    522  409000611074  2018-07-13  INDO GIBL Indiaforensic STL12071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-13          3120.0          NaN    1377075.0
1  2018-07-13        447455.0          NaN     929620.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      521    521  409000611074  2018-07-13      Indfor INCOME INDO REMI12071
1      522    522  409000611074  2018-07-13  INDO GIBL Indiaforensic STL12071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-13          3120.0          NaN    1377075.0
1  2018-07-13        447455.0          NaN     929620.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      533    533  409000611074  2018-07-17      Indfor INCOME INDO REMI16071
1      534    534  409000611074  2018-07-17  INDO GIBL Indiaforensic STL16071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-17          4080.0          NaN    1624940.0
1  2018-07-17        717000.0          NaN     907940.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      533    533  409000611074  2018-07-17      Indfor INCOME INDO REMI16071
1      534    534  409000611074  2018-07-17  INDO GIBL Indiaforensic STL16071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-17          4080.0          NaN    1624940.0
1  2018-07-17        717000.0          NaN     907940.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      533    533  409000611074  2018-07-17      Indfor INCOME INDO REMI16071
1      534    534  409000611074  2018-07-17  INDO GIBL Indiaforensic STL16071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-17          4080.0          NaN    1624940.0
1  2018-07-17        717000.0          NaN     907940.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      533    533  409000611074  2018-07-17      Indfor INCOME INDO REMI16071
1      534    534  409000611074  2018-07-17  INDO GIBL Indiaforensic STL16071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-17          4080.0          NaN    1624940.0
1  2018-07-17        717000.0          NaN     907940.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      537    537  409000611074  2018-07-18      Indfor INCOME INDO REMI17071
1      538    538  409000611074  2018-07-18  INDO GIBL Indiaforensic STL17071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-18          3960.0          NaN    1303980.0
1  2018-07-18        581900.0          NaN     722080.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      537    537  409000611074  2018-07-18      Indfor INCOME INDO REMI17071
1      538    538  409000611074  2018-07-18  INDO GIBL Indiaforensic STL17071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-18          3960.0          NaN    1303980.0
1  2018-07-18        581900.0          NaN     722080.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      537    537  409000611074  2018-07-18      Indfor INCOME INDO REMI17071
1      538    538  409000611074  2018-07-18  INDO GIBL Indiaforensic STL17071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-18          3960.0          NaN    1303980.0
1  2018-07-18        581900.0          NaN     722080.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      537    537  409000611074  2018-07-18      Indfor INCOME INDO REMI17071
1      538    538  409000611074  2018-07-18  INDO GIBL Indiaforensic STL17071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-18          3960.0          NaN    1303980.0
1  2018-07-18        581900.0          NaN     722080.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      545    545  409000611074  2018-07-19      Indfor INCOME INDO REMI18071
1      546    546  409000611074  2018-07-19  INDO GIBL Indiaforensic STL18071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-19          3600.0          NaN    1918480.0
1  2018-07-19        663350.0          NaN    1255130.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      545    545  409000611074  2018-07-19      Indfor INCOME INDO REMI18071
1      546    546  409000611074  2018-07-19  INDO GIBL Indiaforensic STL18071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-19          3600.0          NaN    1918480.0
1  2018-07-19        663350.0          NaN    1255130.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      547    547  409000611074  2018-07-20      Indfor INCOME INDO REMI19071
1      548    548  409000611074  2018-07-20  INDO GIBL Indiaforensic STL19071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-20          1440.0          NaN    1253690.0
1  2018-07-20        135800.0          NaN    1117890.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      550    550  409000611074  2018-07-21      Indfor INCOME INDO REMI20071
1      551    551  409000611074  2018-07-21  INDO GIBL Indiaforensic STL20071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-21          3600.0          NaN    1414290.0
1  2018-07-21        712099.0          NaN     702191.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      554    554  409000611074  2018-07-23      Indfor INCOME INDO REMI22071
1      555    555  409000611074  2018-07-23  INDO GIBL Indiaforensic STL22071
2      556    556  409000611074  2018-07-23      Indfor INCOME INDO REMI21071
3      557    557  409000611074  2018-07-23  INDO GIBL Indiaforensic STL21071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-23           840.0          NaN    2001351.0
1  2018-07-23        145400.0          NaN    1855951.0
2  2018-07-23          1920.0          NaN    1854031.0
3  2018-07-23        240535.0          NaN    1613496.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      561    561  409000611074  2018-07-25      Indfor INCOME INDO REMI24071
1      562    562  409000611074  2018-07-25  INDO GIBL Indiaforensic STL24071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-25          3360.0          NaN    1496196.0
1  2018-07-25        518500.0          NaN     977696.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      561    561  409000611074  2018-07-25      Indfor INCOME INDO REMI24071
1      562    562  409000611074  2018-07-25  INDO GIBL Indiaforensic STL24071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-25          3360.0          NaN    1496196.0
1  2018-07-25        518500.0          NaN     977696.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      561    561  409000611074  2018-07-25      Indfor INCOME INDO REMI24071
1      562    562  409000611074  2018-07-25  INDO GIBL Indiaforensic STL24071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-25          3360.0          NaN    1496196.0
1  2018-07-25        518500.0          NaN     977696.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      565    565  409000611074  2018-07-26      Indfor INCOME INDO REMI25071
1      566    566  409000611074  2018-07-26  INDO GIBL Indiaforensic STL25071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-26          3240.0          NaN    1574456.0
1  2018-07-26        442250.0          NaN    1132206.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      568    568  409000611074  2018-07-27      Indfor INCOME INDO REMI26071
1      569    569  409000611074  2018-07-27  INDO GIBL Indiaforensic STL26071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-27          3240.0          NaN    1428966.0
1  2018-07-27        389600.0          NaN    1039366.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      575    575  409000611074  2018-07-31      Indfor INCOME INDO REMI30071
1      576    576  409000611074  2018-07-31  INDO GIBL Indiaforensic STL30071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-07-31          2280.0          NaN    1509051.0
1  2018-07-31        341400.0          NaN    1167651.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      578    578  409000611074  2018-08-01      Indfor INCOME INDO REMI31071
1      579    579  409000611074  2018-08-01  INDO GIBL Indiaforensic STL31071

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-01          2760.0          NaN    1464891.0
1  2018-08-01        372350.0          NaN    1092541.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      581    581  409000611074  2018-08-02      Indfor INCOME INDO REMI01081
1      582    582  409000611074  2018-08-02  INDO GIBL Indiaforensic STL01081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-02          1080.0          NaN    1391461.0
1  2018-08-02        145500.0          NaN    1245961.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      593    593  409000611074  2018-08-07      Indfor INCOME INDO REMI06081
1      594    594  409000611074  2018-08-07  INDO GIBL Indiaforensic STL06081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-07          3720.0          NaN    1419700.0
1  2018-08-07        457050.0          NaN     962650.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      593    593  409000611074  2018-08-07      Indfor INCOME INDO REMI06081
1      594    594  409000611074  2018-08-07  INDO GIBL Indiaforensic STL06081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-07          3720.0          NaN    1419700.0
1  2018-08-07        457050.0          NaN     962650.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      593    593  409000611074  2018-08-07      Indfor INCOME INDO REMI06081
1      594    594  409000611074  2018-08-07  INDO GIBL Indiaforensic STL06081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-07          3720.0          NaN    1419700.0
1  2018-08-07        457050.0          NaN     962650.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      597    597  409000611074  2018-08-08      Indfor INCOME INDO REMI07081
1      598    598  409000611074  2018-08-08  INDO GIBL Indiaforensic STL07081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-08          3840.0          NaN    1558810.0
1  2018-08-08        662025.0          NaN     896785.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      600    600  409000611074  2018-08-09      Indfor INCOME INDO REMI08081
1      601    601  409000611074  2018-08-09  INDO GIBL Indiaforensic STL08081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-09          3480.0          NaN    1393305.0
1  2018-08-09        556450.0          NaN     836855.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      603    603  409000611074  2018-08-10      Indfor INCOME INDO REMI09081
1      604    604  409000611074  2018-08-10  INDO GIBL Indiaforensic STL09081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-10          2280.0          NaN    1334575.0
1  2018-08-10        336850.0          NaN     997725.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      612    612  409000611074  2018-08-14      Indfor INCOME INDO REMI13081
1      613    613  409000611074  2018-08-14  INDO GIBL Indiaforensic STL13081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-14          3480.0          NaN    1321405.0
1  2018-08-14        517655.0          NaN     803750.0
xxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      615    615  409000611074  2018-08-16      Indfor INCOME INDO REMI14081
1      616    616  409000611074  2018-08-16  INDO GIBL Indiaforensic STL14081
2      617    617  409000611074  2018-08-16      Indfor INCOME INDO REMI15081
3      618    618  409000611074  2018-08-16  INDO GIBL Indiaforensic STL15081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-16          3600.0          NaN    1800150.0
1  2018-08-16        561995.0          NaN    1238155.0
2  2018-08-16          1320.0          NaN    1236835.0
3  2018-08-16        212000.0          NaN    1024835.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      620    620  409000611074  2018-08-17      Indfor INCOME INDO REMI16081
1      621    621  409000611074  2018-08-17  INDO GIBL Indiaforensic STL16081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-17          4440.0          NaN    1520395.0
1  2018-08-17        755505.0          NaN     764890.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      623    623  409000611074  2018-08-18      Indfor INCOME INDO REMI17081
1      624    624  409000611074  2018-08-18  INDO GIBL Indiaforensic STL17081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-18          3960.0          NaN    1160930.0
1  2018-08-18        615328.0          NaN     545602.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      623    623  409000611074  2018-08-18      Indfor INCOME INDO REMI17081
1      624    624  409000611074  2018-08-18  INDO GIBL Indiaforensic STL17081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-18          3960.0          NaN    1160930.0
1  2018-08-18        615328.0          NaN     545602.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      632    632  409000611074  2018-08-21      Indfor INCOME INDO REMI20081
1      633    633  409000611074  2018-08-21  INDO GIBL Indiaforensic STL20081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-21          4200.0          NaN    1658222.0
1  2018-08-21        554751.0          NaN    1103471.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      636    636  409000611074  2018-08-23      Indfor INCOME INDO REMI21081
1      637    637  409000611074  2018-08-23  INDO GIBL Indiaforensic STL21081
2      638    638  409000611074  2018-08-23      Indfor INCOME INDO REMI22081
3      639    639  409000611074  2018-08-23  INDO GIBL Indiaforensic STL22081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-23          5280.0          NaN    1898191.0
1  2018-08-23        912000.0          NaN     986191.0
2  2018-08-23          1800.0          NaN     984391.0
3  2018-08-23        335601.0          NaN     648790.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      636    636  409000611074  2018-08-23      Indfor INCOME INDO REMI21081
1      637    637  409000611074  2018-08-23  INDO GIBL Indiaforensic STL21081
2      638    638  409000611074  2018-08-23      Indfor INCOME INDO REMI22081
3      639    639  409000611074  2018-08-23  INDO GIBL Indiaforensic STL22081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-23          5280.0          NaN    1898191.0
1  2018-08-23        912000.0          NaN     986191.0
2  2018-08-23          1800.0          NaN     984391.0
3  2018-08-23        335601.0          NaN     648790.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      636    636  409000611074  2018-08-23      Indfor INCOME INDO REMI21081
1      637    637  409000611074  2018-08-23  INDO GIBL Indiaforensic STL21081
2      638    638  409000611074  2018-08-23      Indfor INCOME INDO REMI22081
3      639    639  409000611074  2018-08-23  INDO GIBL Indiaforensic STL22081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-23          5280.0          NaN    1898191.0
1  2018-08-23        912000.0          NaN     986191.0
2  2018-08-23          1800.0          NaN     984391.0
3  2018-08-23        335601.0          NaN     648790.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      641    641  409000611074  2018-08-24      Indfor INCOME INDO REMI23081
1      642    642  409000611074  2018-08-24  INDO GIBL Indiaforensic STL23081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-24          2400.0          NaN    1046390.0
1  2018-08-24        338131.0          NaN     708259.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      641    641  409000611074  2018-08-24      Indfor INCOME INDO REMI23081
1      642    642  409000611074  2018-08-24  INDO GIBL Indiaforensic STL23081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-24          2400.0          NaN    1046390.0
1  2018-08-24        338131.0          NaN     708259.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      645    645  409000611074  2018-08-27      Indfor INCOME INDO REMI24081
1      646    646  409000611074  2018-08-27  INDO GIBL Indiaforensic STL24081
2      647    647  409000611074  2018-08-27      Indfor INCOME INDO REMI25081
3      648    648  409000611074  2018-08-27  INDO GIBL Indiaforensic STL25081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-27          1560.0          NaN    1506699.0
1  2018-08-27        230300.0          NaN    1276399.0
2  2018-08-27           720.0          NaN    1275679.0
3  2018-08-27         71080.0          NaN    1204599.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      650    650  409000611074  2018-08-28      Indfor INCOME INDO REMI27081
1      651    651  409000611074  2018-08-28  INDO GIBL Indiaforensic STL27081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-28          4320.0          NaN    1600279.0
1  2018-08-28        518401.0          NaN    1081878.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      653    653  409000611074  2018-08-29      Indfor INCOME INDO REMI28081
1      654    654  409000611074  2018-08-29  INDO GIBL Indiaforensic STL28081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-29          2160.0          NaN    1479718.0
1  2018-08-29        254584.0          NaN    1225134.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      658    658  409000611074  2018-08-31      Indfor INCOME INDO REMI30081
1      659    659  409000611074  2018-08-31  INDO GIBL Indiaforensic STL30081

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-08-31          2280.0          NaN    1269509.0
1  2018-08-31        360425.0          NaN     909084.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE           TRANSACTION DETAILS  \
0      661    661  409000611074  2018-09-01  Indfor INCOME INDO REMI31081
1      662    662  409000611074  2018-09-01           INDO WEIZ STL310818

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-01          3000.0          NaN    1406084.0
1  2018-09-01        414101.0          NaN     991983.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      668    668  409000611074  2018-09-04      Indfor INCOME INDO REMI03091
1      669    669  409000611074  2018-09-04  INDO GIBL Indiaforensic STL03091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-04          1920.0          NaN    1242403.0
1  2018-09-04        228025.0          NaN    1014378.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      673    673  409000611074  2018-09-06      Indfor INCOME INDO REMI05091
1      674    674  409000611074  2018-09-06  INDO GIBL Indiaforensic STL05091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-06          2880.0          NaN    1140318.0
1  2018-09-06        406628.0          NaN     733690.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      679    679  409000611074  2018-09-10      Indfor INCOME INDO REMI07091
1      680    680  409000611074  2018-09-10  INDO GIBL Indiaforensic STL07091
2      681    681  409000611074  2018-09-10      Indfor INCOME INDO REMI08091
3      682    682  409000611074  2018-09-10  INDO GIBL Indiaforensic STL08091
4      683    683  409000611074  2018-09-10      Indfor INCOME INDO REMI09091
5      684    684  409000611074  2018-09-10  INDO GIBL Indiaforensic STL09091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-10          3240.0          NaN    1350492.0
1  2018-09-10        441750.0          NaN     908742.0
2  2018-09-10          2040.0          NaN     906702.0
3  2018-09-10        274751.0          NaN     631951.0
4  2018-09-10           360.0          NaN     631591.0
5  2018-09-10         61600.0          NaN     569991.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      679    679  409000611074  2018-09-10      Indfor INCOME INDO REMI07091
1      680    680  409000611074  2018-09-10  INDO GIBL Indiaforensic STL07091
2      681    681  409000611074  2018-09-10      Indfor INCOME INDO REMI08091
3      682    682  409000611074  2018-09-10  INDO GIBL Indiaforensic STL08091
4      683    683  409000611074  2018-09-10      Indfor INCOME INDO REMI09091
5      684    684  409000611074  2018-09-10  INDO GIBL Indiaforensic STL09091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-10          3240.0          NaN    1350492.0
1  2018-09-10        441750.0          NaN     908742.0
2  2018-09-10          2040.0          NaN     906702.0
3  2018-09-10        274751.0          NaN     631951.0
4  2018-09-10           360.0          NaN     631591.0
5  2018-09-10         61600.0          NaN     569991.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      679    679  409000611074  2018-09-10      Indfor INCOME INDO REMI07091
1      680    680  409000611074  2018-09-10  INDO GIBL Indiaforensic STL07091
2      681    681  409000611074  2018-09-10      Indfor INCOME INDO REMI08091
3      682    682  409000611074  2018-09-10  INDO GIBL Indiaforensic STL08091
4      683    683  409000611074  2018-09-10      Indfor INCOME INDO REMI09091
5      684    684  409000611074  2018-09-10  INDO GIBL Indiaforensic STL09091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-10          3240.0          NaN    1350492.0
1  2018-09-10        441750.0          NaN     908742.0
2  2018-09-10          2040.0          NaN     906702.0
3  2018-09-10        274751.0          NaN     631951.0
4  2018-09-10           360.0          NaN     631591.0
5  2018-09-10         61600.0          NaN     569991.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      690    690  409000611074  2018-09-12      Indfor INCOME INDO REMI11091
1      691    691  409000611074  2018-09-12  INDO GIBL Indiaforensic STL11091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-12          5160.0          NaN    2022855.0
1  2018-09-12        776577.0          NaN    1246278.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      692    692  409000611074  2018-09-14      Indfor INCOME INDO REMI12091
1      693    693  409000611074  2018-09-14  INDO GIBL Indiaforensic STL12091
2      694    694  409000611074  2018-09-14      Indfor INCOME INDO REMI13091
3      695    695  409000611074  2018-09-14  INDO GIBL Indiaforensic STL13091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-14          1800.0          NaN    1244478.0
1  2018-09-14        252025.0          NaN     992453.0
2  2018-09-14          2520.0          NaN     989933.0
3  2018-09-14        395501.0          NaN     594432.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      701    701  409000611074  2018-09-17      Indfor INCOME INDO REMI15091
1      702    702  409000611074  2018-09-17  INDO GIBL Indiaforensic STL15091
2      703    703  409000611074  2018-09-17      Indfor INCOME INDO REMI16091
3      704    704  409000611074  2018-09-17  INDO GIBL Indiaforensic STL16091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-17          1200.0          NaN    2046161.0
1  2018-09-17        223150.0          NaN    1823011.0
2  2018-09-17           120.0          NaN    1822891.0
3  2018-09-17         12500.0          NaN    1810391.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      701    701  409000611074  2018-09-17      Indfor INCOME INDO REMI15091
1      702    702  409000611074  2018-09-17  INDO GIBL Indiaforensic STL15091
2      703    703  409000611074  2018-09-17      Indfor INCOME INDO REMI16091
3      704    704  409000611074  2018-09-17  INDO GIBL Indiaforensic STL16091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-17          1200.0          NaN    2046161.0
1  2018-09-17        223150.0          NaN    1823011.0
2  2018-09-17           120.0          NaN    1822891.0
3  2018-09-17         12500.0          NaN    1810391.0
xxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      714    714  409000611074  2018-09-24      Indfor INCOME INDO REMI20091
1      715    715  409000611074  2018-09-24  INDO GIBL Indiaforensic STL20091
2      716    716  409000611074  2018-09-24      Indfor INCOME INDO REMI21091
3      717    717  409000611074  2018-09-24  INDO GIBL Indiaforensic STL21091
4      718    718  409000611074  2018-09-24      Indfor INCOME INDO REMI22091
5      719    719  409000611074  2018-09-24  INDO GIBL Indiaforensic STL22091
6      720    720  409000611074  2018-09-24      Indfor INCOME INDO REMI23091
7      721    721  409000611074  2018-09-24  INDO GIBL Indiaforensic STL23091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-24          3120.0          NaN    1719748.0
1  2018-09-24        503006.0          NaN    1216742.0
2  2018-09-24          1800.0          NaN    1214942.0
3  2018-09-24        255052.0          NaN     959890.0
4  2018-09-24           600.0          NaN     959290.0
5  2018-09-24         78250.0          NaN     881040.0
6  2018-09-24           120.0          NaN     880920.0
7  2018-09-24          6250.0          NaN     874670.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      714    714  409000611074  2018-09-24      Indfor INCOME INDO REMI20091
1      715    715  409000611074  2018-09-24  INDO GIBL Indiaforensic STL20091
2      716    716  409000611074  2018-09-24      Indfor INCOME INDO REMI21091
3      717    717  409000611074  2018-09-24  INDO GIBL Indiaforensic STL21091
4      718    718  409000611074  2018-09-24      Indfor INCOME INDO REMI22091
5      719    719  409000611074  2018-09-24  INDO GIBL Indiaforensic STL22091
6      720    720  409000611074  2018-09-24      Indfor INCOME INDO REMI23091
7      721    721  409000611074  2018-09-24  INDO GIBL Indiaforensic STL23091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-24          3120.0          NaN    1719748.0
1  2018-09-24        503006.0          NaN    1216742.0
2  2018-09-24          1800.0          NaN    1214942.0
3  2018-09-24        255052.0          NaN     959890.0
4  2018-09-24           600.0          NaN     959290.0
5  2018-09-24         78250.0          NaN     881040.0
6  2018-09-24           120.0          NaN     880920.0
7  2018-09-24          6250.0          NaN     874670.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      714    714  409000611074  2018-09-24      Indfor INCOME INDO REMI20091
1      715    715  409000611074  2018-09-24  INDO GIBL Indiaforensic STL20091
2      716    716  409000611074  2018-09-24      Indfor INCOME INDO REMI21091
3      717    717  409000611074  2018-09-24  INDO GIBL Indiaforensic STL21091
4      718    718  409000611074  2018-09-24      Indfor INCOME INDO REMI22091
5      719    719  409000611074  2018-09-24  INDO GIBL Indiaforensic STL22091
6      720    720  409000611074  2018-09-24      Indfor INCOME INDO REMI23091
7      721    721  409000611074  2018-09-24  INDO GIBL Indiaforensic STL23091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-24          3120.0          NaN    1719748.0
1  2018-09-24        503006.0          NaN    1216742.0
2  2018-09-24          1800.0          NaN    1214942.0
3  2018-09-24        255052.0          NaN     959890.0
4  2018-09-24           600.0          NaN     959290.0
5  2018-09-24         78250.0          NaN     881040.0
6  2018-09-24           120.0          NaN     880920.0
7  2018-09-24          6250.0          NaN     874670.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      726    726  409000611074  2018-09-26      Indfor INCOME INDO REMI25091
1      727    727  409000611074  2018-09-26  INDO GIBL Indiaforensic STL25091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-26          2520.0          NaN    1524145.0
1  2018-09-26        407252.0          NaN    1116893.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      731    731  409000611074  2018-09-28      Indfor INCOME INDO REMI27091
1      732    732  409000611074  2018-09-28  INDO GIBL Indiaforensic STL27091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-09-28          2040.0          NaN    1357483.0
1  2018-09-28        327001.0          NaN    1030482.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      736    736  409000611074  2018-10-01      Indfor INCOME INDO REMI29091
1      737    737  409000611074  2018-10-01  INDO GIBL Indiaforensic STL29091
2      738    738  409000611074  2018-10-01      Indfor INCOME INDO REMI30091
3      739    739  409000611074  2018-10-01  INDO GIBL Indiaforensic STL30091

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-01          2040.0          NaN    1295247.0
1  2018-10-01        333800.0          NaN     961447.0
2  2018-10-01           120.0          NaN     961327.0
3  2018-10-01          5000.0          NaN     956327.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      741    741  409000611074  2018-10-03      Indfor INCOME INDO REMI01101
1      742    742  409000611074  2018-10-03  INDO GIBL Indiaforensic STL01101
2      743    743  409000611074  2018-10-03      Indfor INCOME INDO REMI02101
3      744    744  409000611074  2018-10-03  INDO GIBL Indiaforensic STL02101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-03          3720.0          NaN    1452607.0
1  2018-10-03        529105.0          NaN     923502.0
2  2018-10-03          1200.0          NaN     922302.0
3  2018-10-03        225300.0          NaN     697002.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      741    741  409000611074  2018-10-03      Indfor INCOME INDO REMI01101
1      742    742  409000611074  2018-10-03  INDO GIBL Indiaforensic STL01101
2      743    743  409000611074  2018-10-03      Indfor INCOME INDO REMI02101
3      744    744  409000611074  2018-10-03  INDO GIBL Indiaforensic STL02101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-03          3720.0          NaN    1452607.0
1  2018-10-03        529105.0          NaN     923502.0
2  2018-10-03          1200.0          NaN     922302.0
3  2018-10-03        225300.0          NaN     697002.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      741    741  409000611074  2018-10-03      Indfor INCOME INDO REMI01101
1      742    742  409000611074  2018-10-03  INDO GIBL Indiaforensic STL01101
2      743    743  409000611074  2018-10-03      Indfor INCOME INDO REMI02101
3      744    744  409000611074  2018-10-03  INDO GIBL Indiaforensic STL02101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-03          3720.0          NaN    1452607.0
1  2018-10-03        529105.0          NaN     923502.0
2  2018-10-03          1200.0          NaN     922302.0
3  2018-10-03        225300.0          NaN     697002.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      751    751  409000611074  2018-10-06      Indfor INCOME INDO REMI05101
1      752    752  409000611074  2018-10-06  INDO GIBL Indiaforensic STL05101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-06          1320.0          NaN     989407.0
1  2018-10-06        230751.0          NaN     758656.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      754    754  409000611074  2018-10-08      Indfor INCOME INDO REMI07101
1      755    755  409000611074  2018-10-08  INDO GIBL Indiaforensic STL07101
2      756    756  409000611074  2018-10-08      Indfor INCOME INDO REMI06101
3      757    757  409000611074  2018-10-08  INDO GIBL Indiaforensic STL06101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-08           480.0          NaN    1258176.0
1  2018-10-08         56000.0          NaN    1202176.0
2  2018-10-08          2280.0          NaN    1199896.0
3  2018-10-08        282452.0          NaN     917444.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      759    759  409000611074  2018-10-09      Indfor INCOME INDO REMI08101
1      760    760  409000611074  2018-10-09  INDO GIBL Indiaforensic STL08101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-09          4080.0          NaN    1413364.0
1  2018-10-09        530352.0          NaN     883012.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      765    765  409000611074  2018-10-11      Indfor INCOME INDO REMI10101
1      766    766  409000611074  2018-10-11  INDO GIBL Indiaforensic STL10101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-11          3720.0          NaN    1562289.0
1  2018-10-11        584951.0          NaN     977338.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      768    768  409000611074  2018-10-12      Indfor INCOME INDO REMI11101
1      769    769  409000611074  2018-10-12  INDO GIBL Indiaforensic STL11101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-12          4080.0          NaN    1473258.0
1  2018-10-12        599251.0          NaN     874007.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      772    772  409000611074  2018-10-15      Indfor INCOME INDO REMI12101
1      773    773  409000611074  2018-10-15  INDO GIBL Indiaforensic STL12101
2      774    774  409000611074  2018-10-15      Indfor INCOME INDO REMI13101
3      775    775  409000611074  2018-10-15  INDO GIBL Indiaforensic STL13101
4      776    776  409000611074  2018-10-15      Indfor INCOME INDO REMI14101
5      777    777  409000611074  2018-10-15  INDO GIBL Indiaforensic STL14101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-15          3840.0          NaN    1870167.0
1  2018-10-15        730425.0          NaN    1139742.0
2  2018-10-15          1440.0          NaN    1138302.0
3  2018-10-15        173350.0          NaN     964952.0
4  2018-10-15           360.0          NaN     964592.0
5  2018-10-15         34500.0          NaN     930092.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      772    772  409000611074  2018-10-15      Indfor INCOME INDO REMI12101
1      773    773  409000611074  2018-10-15  INDO GIBL Indiaforensic STL12101
2      774    774  409000611074  2018-10-15      Indfor INCOME INDO REMI13101
3      775    775  409000611074  2018-10-15  INDO GIBL Indiaforensic STL13101
4      776    776  409000611074  2018-10-15      Indfor INCOME INDO REMI14101
5      777    777  409000611074  2018-10-15  INDO GIBL Indiaforensic STL14101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-15          3840.0          NaN    1870167.0
1  2018-10-15        730425.0          NaN    1139742.0
2  2018-10-15          1440.0          NaN    1138302.0
3  2018-10-15        173350.0          NaN     964952.0
4  2018-10-15           360.0          NaN     964592.0
5  2018-10-15         34500.0          NaN     930092.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      779    779  409000611074  2018-10-16      Indfor INCOME INDO REMI15101
1      780    780  409000611074  2018-10-16  INDO GIBL Indiaforensic STL15101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-16          5160.0          NaN    1424932.0
1  2018-10-16        780576.0          NaN     644356.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      785    785  409000611074  2018-10-17      Indfor INCOME INDO REMI16101
1      786    786  409000611074  2018-10-17  INDO GIBL Indiaforensic STL16101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-17          4080.0          NaN    1640276.0
1  2018-10-17        673628.0          NaN     966648.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      785    785  409000611074  2018-10-17      Indfor INCOME INDO REMI16101
1      786    786  409000611074  2018-10-17  INDO GIBL Indiaforensic STL16101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-17          4080.0          NaN    1640276.0

1  2018-10-17        673628.0          NaN     966648.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      785    785  409000611074  2018-10-17      Indfor INCOME INDO REMI16101
1      786    786  409000611074  2018-10-17  INDO GIBL Indiaforensic STL16101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-17          4080.0          NaN    1640276.0
1  2018-10-17        673628.0          NaN     966648.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      785    785  409000611074  2018-10-17      Indfor INCOME INDO REMI16101
1      786    786  409000611074  2018-10-17  INDO GIBL Indiaforensic STL16101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-17          4080.0          NaN    1640276.0
1  2018-10-17        673628.0          NaN     966648.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      785    785  409000611074  2018-10-17      Indfor INCOME INDO REMI16101
1      786    786  409000611074  2018-10-17  INDO GIBL Indiaforensic STL16101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-17          4080.0          NaN    1640276.0
1  2018-10-17        673628.0          NaN     966648.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      794    794  409000611074  2018-10-22      Indfor INCOME INDO REMI20101
1      795    795  409000611074  2018-10-22  INDO GIBL Indiaforensic STL20101
2      796    796  409000611074  2018-10-22      Indfor INCOME INDO REMI21101
3      797    797  409000611074  2018-10-22  INDO GIBL Indiaforensic STL21101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-22          1200.0          NaN    1137566.0
1  2018-10-22        223600.0          NaN     913966.0
2  2018-10-22           120.0          NaN     913846.0
3  2018-10-22         10500.0          NaN     903346.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      799    799  409000611074  2018-10-23      Indfor INCOME INDO REMI22101
1      800    800  409000611074  2018-10-23  INDO GIBL Indiaforensic STL22101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-23          2760.0          NaN    1400586.0
1  2018-10-23        436678.0          NaN     963908.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      802    802  409000611074  2018-10-24      Indfor INCOME INDO REMI23101
1      803    803  409000611074  2018-10-24  INDO GIBL Indiaforensic STL23101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-24          2040.0          NaN    1161868.0
1  2018-10-24        432150.0          NaN     729718.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      812    812  409000611074  2018-10-29      Indfor INCOME INDO REMI26101
1      813    813  409000611074  2018-10-29  INDO GIBL Indiaforensic STL26101
2      814    814  409000611074  2018-10-29      Indfor INCOME INDO REMI27101
3      815    815  409000611074  2018-10-29  INDO GIBL Indiaforensic STL27101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-29          1560.0          NaN    1436434.0
1  2018-10-29        224800.0          NaN    1211634.0
2  2018-10-29          1200.0          NaN    1210434.0
3  2018-10-29        254250.0          NaN     956184.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      812    812  409000611074  2018-10-29      Indfor INCOME INDO REMI26101
1      813    813  409000611074  2018-10-29  INDO GIBL Indiaforensic STL26101
2      814    814  409000611074  2018-10-29      Indfor INCOME INDO REMI27101
3      815    815  409000611074  2018-10-29  INDO GIBL Indiaforensic STL27101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-29          1560.0          NaN    1436434.0
1  2018-10-29        224800.0          NaN    1211634.0
2  2018-10-29          1200.0          NaN    1210434.0
3  2018-10-29        254250.0          NaN     956184.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      812    812  409000611074  2018-10-29      Indfor INCOME INDO REMI26101
1      813    813  409000611074  2018-10-29  INDO GIBL Indiaforensic STL26101
2      814    814  409000611074  2018-10-29      Indfor INCOME INDO REMI27101
3      815    815  409000611074  2018-10-29  INDO GIBL Indiaforensic STL27101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-29          1560.0          NaN    1436434.0
1  2018-10-29        224800.0          NaN    1211634.0
2  2018-10-29          1200.0          NaN    1210434.0
3  2018-10-29        254250.0          NaN     956184.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      816    816  409000611074  2018-10-30      Indfor INCOME INDO REMI29101
1      817    817  409000611074  2018-10-30  INDO GIBL Indiaforensic STL29101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-30          3360.0          NaN     952824.0
1  2018-10-30        364175.0          NaN     588649.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      816    816  409000611074  2018-10-30      Indfor INCOME INDO REMI29101
1      817    817  409000611074  2018-10-30  INDO GIBL Indiaforensic STL29101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-30          3360.0          NaN     952824.0
1  2018-10-30        364175.0          NaN     588649.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      820    820  409000611074  2018-10-31      Indfor INCOME INDO REMI30101
1      821    821  409000611074  2018-10-31  INDO GIBL Indiaforensic STL30101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-31          2520.0          NaN    1086129.0
1  2018-10-31        274602.0          NaN     811527.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      820    820  409000611074  2018-10-31      Indfor INCOME INDO REMI30101
1      821    821  409000611074  2018-10-31  INDO GIBL Indiaforensic STL30101

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-10-31          2520.0          NaN    1086129.0
1  2018-10-31        274602.0          NaN     811527.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      828    828  409000611074  2018-11-03      Indfor INCOME INDO REMI02111
1      829    829  409000611074  2018-11-03  INDO GIBL Indiaforensic STL02111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-03          2640.0          NaN     873307.0
1  2018-11-03        369251.0          NaN     504056.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      831    831  409000611074  2018-11-05      Indfor INCOME INDO REMI03111
1      832    832  409000611074  2018-11-05  INDO GIBL Indiaforensic STL03111
2      833    833  409000611074  2018-11-05      Indfor INCOME INDO REMI04111
3      834    834  409000611074  2018-11-05  INDO GIBL Indiaforensic STL04111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-05          2280.0          NaN    1001776.0
1  2018-11-05        323726.0          NaN     678050.0
2  2018-11-05           840.0          NaN     677210.0
3  2018-11-05        129000.0          NaN     548210.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      837    837  409000611074  2018-11-06      Indfor INCOME INDO REMI05111
1      838    838  409000611074  2018-11-06  INDO GIBL Indiaforensic STL05111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-06          4920.0          NaN    1543290.0
1  2018-11-06        807502.0          NaN     735788.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      837    837  409000611074  2018-11-06      Indfor INCOME INDO REMI05111
1      838    838  409000611074  2018-11-06  INDO GIBL Indiaforensic STL05111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-06          4920.0          NaN    1543290.0
1  2018-11-06        807502.0          NaN     735788.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      841    841  409000611074  2018-11-09      Indfor INCOME INDO REMI06111
1      842    842  409000611074  2018-11-09  INDO GIBL Indiaforensic STL06111
2      843    843  409000611074  2018-11-09      Indfor INCOME INDO REMI07111
3      844    844  409000611074  2018-11-09  INDO GIBL Indiaforensic STL07111
4      845    845  409000611074  2018-11-09      Indfor INCOME INDO REMI08111
5      846    846  409000611074  2018-11-09  INDO GIBL Indiaforensic STL08111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-09          4920.0          NaN    1730868.0
1  2018-11-09        780026.0          NaN     950842.0
2  2018-11-09          1320.0          NaN     949522.0
3  2018-11-09        153513.0          NaN     796009.0
4  2018-11-09           600.0          NaN     795409.0
5  2018-11-09        102725.0          NaN     692684.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      850    850  409000611074  2018-11-12      Indfor INCOME INDO REMI09111
1      851    851  409000611074  2018-11-12  INDO GIBL Indiaforensic STL09111
2      852    852  409000611074  2018-11-12      Indfor INCOME INDO REMI11111
3      853    853  409000611074  2018-11-12  INDO GIBL Indiaforensic STL11111
4      854    854  409000611074  2018-11-12      Indfor INCOME INDO REMI10111
5      855    855  409000611074  2018-11-12  INDO GIBL Indiaforensic STL10111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-12          2040.0          NaN    1590644.0
1  2018-11-12        478599.0          NaN    1112045.0
2  2018-11-12           120.0          NaN    1111925.0
3  2018-11-12          8000.0          NaN    1103925.0
4  2018-11-12          2040.0          NaN    1101885.0
5  2018-11-12        284926.0          NaN     816959.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      850    850  409000611074  2018-11-12      Indfor INCOME INDO REMI09111
1      851    851  409000611074  2018-11-12  INDO GIBL Indiaforensic STL09111
2      852    852  409000611074  2018-11-12      Indfor INCOME INDO REMI11111
3      853    853  409000611074  2018-11-12  INDO GIBL Indiaforensic STL11111
4      854    854  409000611074  2018-11-12      Indfor INCOME INDO REMI10111
5      855    855  409000611074  2018-11-12  INDO GIBL Indiaforensic STL10111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-12          2040.0          NaN    1590644.0
1  2018-11-12        478599.0          NaN    1112045.0
2  2018-11-12           120.0          NaN    1111925.0
3  2018-11-12          8000.0          NaN    1103925.0
4  2018-11-12          2040.0          NaN    1101885.0
5  2018-11-12        284926.0          NaN     816959.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      850    850  409000611074  2018-11-12      Indfor INCOME INDO REMI09111
1      851    851  409000611074  2018-11-12  INDO GIBL Indiaforensic STL09111
2      852    852  409000611074  2018-11-12      Indfor INCOME INDO REMI11111
3      853    853  409000611074  2018-11-12  INDO GIBL Indiaforensic STL11111
4      854    854  409000611074  2018-11-12      Indfor INCOME INDO REMI10111
5      855    855  409000611074  2018-11-12  INDO GIBL Indiaforensic STL10111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-12          2040.0          NaN    1590644.0
1  2018-11-12        478599.0          NaN    1112045.0
2  2018-11-12           120.0          NaN    1111925.0
3  2018-11-12          8000.0          NaN    1103925.0
4  2018-11-12          2040.0          NaN    1101885.0
5  2018-11-12        284926.0          NaN     816959.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      857    857  409000611074  2018-11-13      Indfor INCOME INDO REMI12111
1      858    858  409000611074  2018-11-13  INDO GIBL Indiaforensic STL12111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-13          2280.0          NaN    1014679.0
1  2018-11-13        354000.0          NaN     660679.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      857    857  409000611074  2018-11-13      Indfor INCOME INDO REMI12111
1      858    858  409000611074  2018-11-13  INDO GIBL Indiaforensic STL12111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-13          2280.0          NaN    1014679.0
1  2018-11-13        354000.0          NaN     660679.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      863    863  409000611074  2018-11-14      Indfor INCOME INDO REMI13111
1      864    864  409000611074  2018-11-14  INDO GIBL Indiaforensic STL13111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-14          4080.0          NaN    1656599.0
1  2018-11-14        800876.0          NaN     855723.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      863    863  409000611074  2018-11-14      Indfor INCOME INDO REMI13111
1      864    864  409000611074  2018-11-14  INDO GIBL Indiaforensic STL13111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-14          4080.0          NaN    1656599.0
1  2018-11-14        800876.0          NaN     855723.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      866    866  409000611074  2018-11-15      Indfor INCOME INDO REMI14111
1      867    867  409000611074  2018-11-15  INDO GIBL Indiaforensic STL14111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-15          2160.0          NaN    1153563.0
1  2018-11-15        404700.0          NaN     748863.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      866    866  409000611074  2018-11-15      Indfor INCOME INDO REMI14111
1      867    867  409000611074  2018-11-15  INDO GIBL Indiaforensic STL14111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-15          2160.0          NaN    1153563.0

1  2018-11-15        404700.0          NaN     748863.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      869    869  409000611074  2018-11-16      Indfor INCOME INDO REMI15111
1      870    870  409000611074  2018-11-16  INDO GIBL Indiaforensic STL15111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-16          3000.0          NaN    1045863.0
1  2018-11-16        580226.0          NaN     465637.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      873    873  409000611074  2018-11-17      Indfor INCOME INDO REMI16111
1      874    874  409000611074  2018-11-17  INDO GIBL Indiaforensic STL16111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-17          3000.0          NaN    1262637.0
1  2018-11-17        583076.0          NaN     679561.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      873    873  409000611074  2018-11-17      Indfor INCOME INDO REMI16111
1      874    874  409000611074  2018-11-17  INDO GIBL Indiaforensic STL16111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-17          3000.0          NaN    1262637.0
1  2018-11-17        583076.0          NaN     679561.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      873    873  409000611074  2018-11-17      Indfor INCOME INDO REMI16111
1      874    874  409000611074  2018-11-17  INDO GIBL Indiaforensic STL16111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-17          3000.0          NaN    1262637.0
1  2018-11-17        583076.0          NaN     679561.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      882    882  409000611074  2018-11-20      Indfor INCOME INDO REMI19111
1      883    883  409000611074  2018-11-20  INDO GIBL Indiaforensic STL19111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-20          3600.0          NaN    1507118.0
1  2018-11-20        613175.0          NaN     893943.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      882    882  409000611074  2018-11-20      Indfor INCOME INDO REMI19111
1      883    883  409000611074  2018-11-20  INDO GIBL Indiaforensic STL19111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-20          3600.0          NaN    1507118.0
1  2018-11-20        613175.0          NaN     893943.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      886    886  409000611074  2018-11-22      Indfor INCOME INDO REMI20111
1      887    887  409000611074  2018-11-22  INDO GIBL Indiaforensic STL20111
2      888    888  409000611074  2018-11-22      Indfor INCOME INDO REMI21111
3      889    889  409000611074  2018-11-22  INDO GIBL Indiaforensic STL21111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-22          3960.0          NaN    1689983.0
1  2018-11-22        628403.0          NaN    1061580.0
2  2018-11-22          1800.0          NaN    1059780.0
3  2018-11-22        250951.0          NaN     808829.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      886    886  409000611074  2018-11-22      Indfor INCOME INDO REMI20111
1      887    887  409000611074  2018-11-22  INDO GIBL Indiaforensic STL20111
2      888    888  409000611074  2018-11-22      Indfor INCOME INDO REMI21111
3      889    889  409000611074  2018-11-22  INDO GIBL Indiaforensic STL21111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-22          3960.0          NaN    1689983.0
1  2018-11-22        628403.0          NaN    1061580.0
2  2018-11-22          1800.0          NaN    1059780.0
3  2018-11-22        250951.0          NaN     808829.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      886    886  409000611074  2018-11-22      Indfor INCOME INDO REMI20111
1      887    887  409000611074  2018-11-22  INDO GIBL Indiaforensic STL20111
2      888    888  409000611074  2018-11-22      Indfor INCOME INDO REMI21111
3      889    889  409000611074  2018-11-22  INDO GIBL Indiaforensic STL21111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-22          3960.0          NaN    1689983.0
1  2018-11-22        628403.0          NaN    1061580.0
2  2018-11-22          1800.0          NaN    1059780.0
3  2018-11-22        250951.0          NaN     808829.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      893    893  409000611074  2018-11-26      Indfor INCOME INDO REMI25111
1      894    894  409000611074  2018-11-26  INDO GIBL Indiaforensic STL25111
2      895    895  409000611074  2018-11-26      Indfor INCOME INDO REMI24111
3      896    896  409000611074  2018-11-26  INDO GIBL Indiaforensic STL24111
4      897    897  409000611074  2018-11-26      Indfor INCOME INDO REMI23111
5      898    898  409000611074  2018-11-26  INDO GIBL Indiaforensic STL23111
6      899    899  409000611074  2018-11-26      Indfor INCOME INDO REMI22111
7      900    900  409000611074  2018-11-26  INDO GIBL Indiaforensic STL22111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-26           480.0          NaN    1808349.0
1  2018-11-26         63600.0          NaN    1744749.0
2  2018-11-26           360.0          NaN    1744389.0
3  2018-11-26         49700.0          NaN    1694689.0
4  2018-11-26          1560.0          NaN    1693129.0
5  2018-11-26        220402.0          NaN    1472727.0
6  2018-11-26          2280.0          NaN    1470447.0
7  2018-11-26        334100.0          NaN    1136347.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      902    902  409000611074  2018-11-27      Indfor INCOME INDO REMI26111
1      903    903  409000611074  2018-11-27  INDO GIBL Indiaforensic STL26111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-27          4440.0          NaN    1531907.0
1  2018-11-27        615817.0          NaN     916090.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      902    902  409000611074  2018-11-27      Indfor INCOME INDO REMI26111
1      903    903  409000611074  2018-11-27  INDO GIBL Indiaforensic STL26111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-27          4440.0          NaN    1531907.0
1  2018-11-27        615817.0          NaN     916090.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      906    906  409000611074  2018-11-28      Indfor INCOME INDO REMI27111
1      907    907  409000611074  2018-11-28  INDO GIBL Indiaforensic STL27111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-28          2760.0          NaN    1613330.0
1  2018-11-28        508126.0          NaN    1105204.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      911    911  409000611074  2018-11-30      Indfor INCOME INDO REMI29111
1      912    912  409000611074  2018-11-30  INDO GIBL Indiaforensic STL29111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-11-30          1800.0          NaN    1174461.0
1  2018-11-30        247700.0          NaN     926761.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      914    914  409000611074  2018-12-01      Indfor INCOME INDO REMI30111
1      915    915  409000611074  2018-12-01  INDO GIBL Indiaforensic STL30111

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-01          3360.0          NaN    1323401.0
1  2018-12-01        510703.0          NaN     812698.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      917    917  409000611074  2018-12-03      Indfor INCOME INDO REMI02121
1      918    918  409000611074  2018-12-03  INDO GIBL Indiaforensic STL02121
2      919    919  409000611074  2018-12-03      Indfor INCOME INDO REMI01121
3      920    920  409000611074  2018-12-03  INDO GIBL Indiaforensic STL01121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-03           120.0          NaN    1212578.0
1  2018-12-03          5000.0          NaN    1207578.0
2  2018-12-03           840.0          NaN    1206738.0
3  2018-12-03        135500.0          NaN    1071238.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      927    927  409000611074  2018-12-06      Indfor INCOME INDO REMI05121
1      928    928  409000611074  2018-12-06  INDO GIBL Indiaforensic STL05121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-06          2760.0          NaN    1586397.0
1  2018-12-06        437150.0          NaN    1149247.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      929    929  409000611074  2018-12-07      Indfor INCOME INDO REMI06121
1      930    930  409000611074  2018-12-07  INDO GIBL Indiaforensic STL06121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-07          2640.0          NaN    1146607.0
1  2018-12-07        397925.0          NaN     748682.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      929    929  409000611074  2018-12-07      Indfor INCOME INDO REMI06121
1      930    930  409000611074  2018-12-07  INDO GIBL Indiaforensic STL06121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-07          2640.0          NaN    1146607.0
1  2018-12-07        397925.0          NaN     748682.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      940    940  409000611074  2018-12-11      Indfor INCOME INDO REMI10121
1      941    941  409000611074  2018-12-11  INDO GIBL Indiaforensic STL10121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-11          4560.0          NaN    1722993.0
1  2018-12-11        776851.0          NaN     946142.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      943    943  409000611074  2018-12-12      Indfor INCOME INDO REMI11121
1      944    944  409000611074  2018-12-12  INDO GIBL Indiaforensic STL11121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-12          3360.0          NaN    1442782.0
1  2018-12-12        358750.0          NaN    1084032.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      943    943  409000611074  2018-12-12      Indfor INCOME INDO REMI11121
1      944    944  409000611074  2018-12-12  INDO GIBL Indiaforensic STL11121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-12          3360.0          NaN    1442782.0
1  2018-12-12        358750.0          NaN    1084032.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      946    946  409000611074  2018-12-13      Indfor INCOME INDO REMI12121
1      947    947  409000611074  2018-12-13  INDO GIBL Indiaforensic STL12121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-13          3360.0          NaN    1580672.0
1  2018-12-13        596375.0          NaN     984297.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      949    949  409000611074  2018-12-14      Indfor INCOME INDO REMI13121
1      950    950  409000611074  2018-12-14  INDO GIBL Indiaforensic STL13121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-14          2880.0          NaN    1481417.0
1  2018-12-14        419450.0          NaN    1061967.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      956    956  409000611074  2018-12-17      Indfor INCOME INDO REMI16121
1      957    957  409000611074  2018-12-17  INDO GIBL Indiaforensic STL16121
2      958    958  409000611074  2018-12-17      Indfor INCOME INDO REMI15121
3      959    959  409000611074  2018-12-17  INDO GIBL Indiaforensic STL15121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-17           360.0          NaN    1935822.0
1  2018-12-17         33549.0          NaN    1902273.0
2  2018-12-17          1680.0          NaN    1900593.0
3  2018-12-17        288851.0          NaN    1611742.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      956    956  409000611074  2018-12-17      Indfor INCOME INDO REMI16121
1      957    957  409000611074  2018-12-17  INDO GIBL Indiaforensic STL16121
2      958    958  409000611074  2018-12-17      Indfor INCOME INDO REMI15121
3      959    959  409000611074  2018-12-17  INDO GIBL Indiaforensic STL15121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-17           360.0          NaN    1935822.0
1  2018-12-17         33549.0          NaN    1902273.0
2  2018-12-17          1680.0          NaN    1900593.0
3  2018-12-17        288851.0          NaN    1611742.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      960    960  409000611074  2018-12-18      Indfor INCOME INDO REMI17121
1      961    961  409000611074  2018-12-18  INDO GIBL Indiaforensic STL17121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-18          4440.0          NaN    1607302.0
1  2018-12-18        662777.0          NaN     944525.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx

   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      963    963  409000611074  2018-12-19      Indfor INCOME INDO REMI18121
1      964    964  409000611074  2018-12-19  INDO GIBL Indiaforensic STL18121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-19          3480.0          NaN    1441045.0
1  2018-12-19        616950.0          NaN     824095.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      966    966  409000611074  2018-12-20      Indfor INCOME INDO REMI19121
1      967    967  409000611074  2018-12-20  INDO GIBL Indiaforensic STL19121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-20          3120.0          NaN    1220975.0
1  2018-12-20        428150.0          NaN     792825.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      969    969  409000611074  2018-12-21      Indfor INCOME INDO REMI20121
1      970    970  409000611074  2018-12-21  INDO GIBL Indiaforensic STL20121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-21          2640.0          NaN    1290185.0
1  2018-12-21        425752.0          NaN     864433.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      972    972  409000611074  2018-12-24      Indfor INCOME INDO REMI23121
1      973    973  409000611074  2018-12-24  INDO GIBL Indiaforensic STL23121
2      974    974  409000611074  2018-12-24      Indfor INCOME INDO REMI22121
3      975    975  409000611074  2018-12-24  INDO GIBL Indiaforensic STL22121
4      976    976  409000611074  2018-12-24      Indfor INCOME INDO REMI21121
5      977    977  409000611074  2018-12-24  INDO GIBL Indiaforensic STL21121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-24           120.0          NaN    1364313.0
1  2018-12-24         20000.0          NaN    1344313.0
2  2018-12-24           960.0          NaN    1343353.0
3  2018-12-24        130600.0          NaN    1212753.0
4  2018-12-24          2760.0          NaN    1209993.0
5  2018-12-24        422577.0          NaN     787416.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      972    972  409000611074  2018-12-24      Indfor INCOME INDO REMI23121
1      973    973  409000611074  2018-12-24  INDO GIBL Indiaforensic STL23121
2      974    974  409000611074  2018-12-24      Indfor INCOME INDO REMI22121
3      975    975  409000611074  2018-12-24  INDO GIBL Indiaforensic STL22121
4      976    976  409000611074  2018-12-24      Indfor INCOME INDO REMI21121
5      977    977  409000611074  2018-12-24  INDO GIBL Indiaforensic STL21121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-24           120.0          NaN    1364313.0
1  2018-12-24         20000.0          NaN    1344313.0
2  2018-12-24           960.0          NaN    1343353.0
3  2018-12-24        130600.0          NaN    1212753.0
4  2018-12-24          2760.0          NaN    1209993.0
5  2018-12-24        422577.0          NaN     787416.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      980    980  409000611074  2018-12-26      Indfor INCOME INDO REMI25121
1      981    981  409000611074  2018-12-26  INDO GIBL Indiaforensic STL25121
2      982    982  409000611074  2018-12-26      Indfor INCOME INDO REMI24121
3      983    983  409000611074  2018-12-26  INDO GIBL Indiaforensic STL24121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-26          1320.0          NaN    1686096.0
1  2018-12-26        173441.0          NaN    1512655.0
2  2018-12-26          4680.0          NaN    1507975.0
3  2018-12-26        692917.0          NaN     815058.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      985    985  409000611074  2018-12-27      Indfor INCOME INDO REMI26121
1      986    986  409000611074  2018-12-27  INDO GIBL Indiaforensic STL26121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-27          1320.0          NaN    1313738.0
1  2018-12-27        250849.0          NaN    1062889.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      988    988  409000611074  2018-12-28      Indfor INCOME INDO REMI27121
1      989    989  409000611074  2018-12-28  INDO GIBL Indiaforensic STL27121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-28          4080.0          NaN    1558809.0
1  2018-12-28        625478.0          NaN     933331.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      991    991  409000611074  2018-12-29      Indfor INCOME INDO REMI28121
1      992    992  409000611074  2018-12-29  INDO GIBL Indiaforensic STL28121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-29          1320.0          NaN    1332011.0
1  2018-12-29        153500.0          NaN    1178511.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      994    994  409000611074  2018-12-31      Indfor INCOME INDO REMI30121
1      995    995  409000611074  2018-12-31  INDO GIBL Indiaforensic STL30121
2      996    996  409000611074  2018-12-31      Indfor INCOME INDO REMI29121
3      997    997  409000611074  2018-12-31  INDO GIBL Indiaforensic STL29121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2018-12-31           240.0          NaN    1578271.0
1  2018-12-31         68700.0          NaN    1509571.0
2  2018-12-31          1200.0          NaN    1508371.0
3  2018-12-31        200550.0          NaN    1307821.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      999    999  409000611074  2019-01-01      Indfor INCOME INDO REMI31121
1     1000   1000  409000611074  2019-01-01  INDO GIBL Indiaforensic STL31121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-01          4560.0          NaN    1703261.0
1  2019-01-01        776077.0          NaN     927184.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0      999    999  409000611074  2019-01-01      Indfor INCOME INDO REMI31121
1     1000   1000  409000611074  2019-01-01  INDO GIBL Indiaforensic STL31121

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-01          4560.0          NaN    1703261.0
1  2019-01-01        776077.0          NaN     927184.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1003   1003  409000611074  2019-01-02      Indfor INCOME INDO REMI01011
1     1004   1004  409000611074  2019-01-02  INDO GIBL Indiaforensic STL01011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-02          2400.0          NaN    1524784.0
1  2019-01-02        408376.0          NaN    1116408.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1006   1006  409000611074  2019-01-03      Indfor INCOME INDO REMI02011
1     1007   1007  409000611074  2019-01-03  INDO GIBL Indiaforensic STL02011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-03          5160.0          NaN    1511248.0
1  2019-01-03        826831.0          NaN     684417.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1006   1006  409000611074  2019-01-03      Indfor INCOME INDO REMI02011
1     1007   1007  409000611074  2019-01-03  INDO GIBL Indiaforensic STL02011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-03          5160.0          NaN    1511248.0
1  2019-01-03        826831.0          NaN     684417.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1010   1010  409000611074  2019-01-04      Indfor INCOME INDO REMI03011
1     1011   1011  409000611074  2019-01-04  INDO GIBL Indiaforensic STL03011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-04          3240.0          NaN    1481177.0
1  2019-01-04        601604.0          NaN     879573.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1010   1010  409000611074  2019-01-04      Indfor INCOME INDO REMI03011
1     1011   1011  409000611074  2019-01-04  INDO GIBL Indiaforensic STL03011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-04          3240.0          NaN    1481177.0
1  2019-01-04        601604.0          NaN     879573.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1022   1022  409000611074  2019-01-08      Indfor INCOME INDO REMI07011
1     1023   1023  409000611074  2019-01-08  INDO GIBL Indiaforensic STL07011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-08          3960.0          NaN    1557236.0
1  2019-01-08        613279.0          NaN     943957.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1022   1022  409000611074  2019-01-08      Indfor INCOME INDO REMI07011
1     1023   1023  409000611074  2019-01-08  INDO GIBL Indiaforensic STL07011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-08          3960.0          NaN    1557236.0
1  2019-01-08        613279.0          NaN     943957.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1022   1022  409000611074  2019-01-08      Indfor INCOME INDO REMI07011
1     1023   1023  409000611074  2019-01-08  INDO GIBL Indiaforensic STL07011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-08          3960.0          NaN    1557236.0
1  2019-01-08        613279.0          NaN     943957.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1025   1025  409000611074  2019-01-09      Indfor INCOME INDO REMI08011
1     1026   1026  409000611074  2019-01-09  INDO GIBL Indiaforensic STL08011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-09          3720.0          NaN    1240237.0
1  2019-01-09        674030.0          NaN     566207.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1025   1025  409000611074  2019-01-09      Indfor INCOME INDO REMI08011
1     1026   1026  409000611074  2019-01-09  INDO GIBL Indiaforensic STL08011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-09          3720.0          NaN    1240237.0
1  2019-01-09        674030.0          NaN     566207.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1029   1029  409000611074  2019-01-10      Indfor INCOME INDO REMI09011
1     1030   1030  409000611074  2019-01-10  INDO GIBL Indiaforensic STL09011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-10          1920.0          NaN    1364287.0
1  2019-01-10        293700.0          NaN    1070587.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1032   1032  409000611074  2019-01-11      Indfor INCOME INDO REMI10011
1     1033   1033  409000611074  2019-01-11  INDO GIBL Indiaforensic STL10011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-11          2400.0          NaN    1368187.0
1  2019-01-11        391453.0          NaN     976734.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1032   1032  409000611074  2019-01-11      Indfor INCOME INDO REMI10011
1     1033   1033  409000611074  2019-01-11  INDO GIBL Indiaforensic STL10011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-11          2400.0          NaN    1368187.0
1  2019-01-11        391453.0          NaN     976734.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1036   1036  409000611074  2019-01-14      Indfor INCOME INDO REMI11011
1     1037   1037  409000611074  2019-01-14  INDO GIBL Indiaforensic STL11011
2     1038   1038  409000611074  2019-01-14      Indfor INCOME INDO REMI12011
3     1039   1039  409000611074  2019-01-14  INDO GIBL Indiaforensic STL12011
4     1040   1040  409000611074  2019-01-14      Indfor INCOME INDO REMI13011
5     1041   1041  409000611074  2019-01-14  INDO GIBL Indiaforensic STL13011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-14          4560.0          NaN    1772174.0
1  2019-01-14        727659.0          NaN    1044515.0
2  2019-01-14          2520.0          NaN    1041995.0
3  2019-01-14        344650.0          NaN     697345.0
4  2019-01-14           240.0          NaN     697105.0
5  2019-01-14         50000.0          NaN     647105.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1036   1036  409000611074  2019-01-14      Indfor INCOME INDO REMI11011
1     1037   1037  409000611074  2019-01-14  INDO GIBL Indiaforensic STL11011
2     1038   1038  409000611074  2019-01-14      Indfor INCOME INDO REMI12011
3     1039   1039  409000611074  2019-01-14  INDO GIBL Indiaforensic STL12011
4     1040   1040  409000611074  2019-01-14      Indfor INCOME INDO REMI13011
5     1041   1041  409000611074  2019-01-14  INDO GIBL Indiaforensic STL13011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-14          4560.0          NaN    1772174.0
1  2019-01-14        727659.0          NaN    1044515.0
2  2019-01-14          2520.0          NaN    1041995.0
3  2019-01-14        344650.0          NaN     697345.0
4  2019-01-14           240.0          NaN     697105.0
5  2019-01-14         50000.0          NaN     647105.0
xxxxxxxxxxxxxxxxxxxxxx

xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1044   1044  409000611074  2019-01-15      Indfor INCOME INDO REMI14011
1     1045   1045  409000611074  2019-01-15  INDO GIBL Indiaforensic STL14011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-15          3600.0          NaN    1243505.0
1  2019-01-15        473626.0          NaN     769879.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1047   1047  409000611074  2019-01-16      Indfor INCOME INDO REMI15011
1     1048   1048  409000611074  2019-01-16  INDO GIBL Indiaforensic STL15011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-16           960.0          NaN    1068919.0
1  2019-01-16        108200.0          NaN     960719.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1050   1050  409000611074  2019-01-17      Indfor INCOME INDO REMI16011
1     1051   1051  409000611074  2019-01-17  INDO GIBL Indiaforensic STL16011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-17          3000.0          NaN    1457719.0
1  2019-01-17        446201.0          NaN    1011518.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1053   1053  409000611074  2019-01-18      Indfor INCOME INDO REMI17011
1     1054   1054  409000611074  2019-01-18  INDO GIBL Indiaforensic STL17011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-18          3600.0          NaN    1407918.0
1  2019-01-18        628628.0          NaN     779290.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1056   1056  409000611074  2019-01-19      Indfor INCOME INDO REMI18011
1     1057   1057  409000611074  2019-01-19  INDO GIBL Indiaforensic STL18011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-19          1440.0          NaN    1277850.0
1  2019-01-19        229800.0          NaN    1048050.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1056   1056  409000611074  2019-01-19      Indfor INCOME INDO REMI18011
1     1057   1057  409000611074  2019-01-19  INDO GIBL Indiaforensic STL18011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-19          1440.0          NaN    1277850.0
1  2019-01-19        229800.0          NaN    1048050.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1060   1060  409000611074  2019-01-21      Indfor INCOME INDO REMI19011
1     1061   1061  409000611074  2019-01-21  INDO GIBL Indiaforensic STL19011
2     1062   1062  409000611074  2019-01-21      Indfor INCOME INDO REMI20011
3     1063   1063  409000611074  2019-01-21  INDO GIBL Indiaforensic STL20011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-21           960.0          NaN    1647090.0
1  2019-01-21         98900.0          NaN    1548190.0
2  2019-01-21           480.0          NaN    1547710.0
3  2019-01-21         96200.0          NaN    1451510.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1065   1065  409000611074  2019-01-22      Indfor INCOME INDO REMI21011
1     1066   1066  409000611074  2019-01-22  INDO GIBL Indiaforensic STL21011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-22          4080.0          NaN    1747430.0
1  2019-01-22        602930.0          NaN    1144500.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1068   1068  409000611074  2019-01-23      Indfor INCOME INDO REMI22011
1     1069   1069  409000611074  2019-01-23  INDO GIBL Indiaforensic STL22011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-23          3720.0          NaN    1540780.0
1  2019-01-23        589137.0          NaN     951643.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1071   1071  409000611074  2019-01-24      Indfor INCOME INDO REMI23011
1     1072   1072  409000611074  2019-01-24  INDO GIBL Indiaforensic STL23011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-24          2880.0          NaN    1448763.0
1  2019-01-24        388327.0          NaN    1060436.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1074   1074  409000611074  2019-01-25      Indfor INCOME INDO REMI24011
1     1075   1075  409000611074  2019-01-25  INDO GIBL Indiaforensic STL24011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-25          2040.0          NaN    1558396.0
1  2019-01-25        245413.0          NaN    1312983.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1077   1077  409000611074  2019-01-28      Indfor INCOME INDO REMI25011
1     1078   1078  409000611074  2019-01-28  INDO GIBL Indiaforensic STL25011
2     1079   1079  409000611074  2019-01-28      Indfor INCOME INDO REMI26011
3     1080   1080  409000611074  2019-01-28  INDO GIBL Indiaforensic STL26011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-28          1920.0          NaN    1611063.0
1  2019-01-28        466124.0          NaN    1144939.0
2  2019-01-28           360.0          NaN    1144579.0
3  2019-01-28         17500.0          NaN    1127079.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1082   1082  409000611074  2019-01-29      Indfor INCOME INDO REMI28011
1     1083   1083  409000611074  2019-01-29  INDO GIBL Indiaforensic STL28011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-29          2520.0          NaN    1524559.0
1  2019-01-29        299125.0          NaN    1225434.0
xxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxx
   level_0  index    Account No        DATE               TRANSACTION DETAILS  \
0     1087   1087  409000611074  2019-01-31      Indfor INCOME INDO REMI30011
1     1088   1088  409000611074  2019-01-31  INDO GIBL Indiaforensic STL30011

   VALUE DATE  WITHDRAWAL AMT  DEPOSIT AMT  BALANCE AMT
0  2019-01-31          1200.0          NaN    1119822.0
1  2019-01-31        224051.0          NaN     895771.0
xxxxxxxxxxxxxxxxxxxxxx

In [17]:
from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

In [29]:
similar(bank.loc[116172]["TRANSACTION DETAILS"], bank.loc[116174]["TRANSACTION DETAILS"])

0.7857142857142857

In [31]:
from fuzzywuzzy import fuzz

print(fuzz.ratio(bank.loc[116172]["TRANSACTION DETAILS"], bank.loc[116174]["TRANSACTION DETAILS"]))

79